
import { Hospital } from './types';

export const createSlug = (name: string) => {
  return name.toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)+/g, '');
};

export const CITY_COORDINATES: Record<string, { lat: number; lng: number }> = {
  // Asia
  'london': { lat: 51.5074, lng: -0.1278 },
  'singapore': { lat: 1.3521, lng: 103.8198 },
  'bangkok': { lat: 13.7563, lng: 100.5018 },
  'jakarta': { lat: -6.2088, lng: 106.8456 },
  'kuala lumpur': { lat: 3.1390, lng: 101.6869 },
  'seoul': { lat: 37.5665, lng: 126.9780 },
  'tokyo': { lat: 35.6762, lng: 139.6503 },
  'hong kong': { lat: 22.3193, lng: 114.1694 },
  'mumbai': { lat: 19.0760, lng: 72.8777 },
  'delhi': { lat: 28.6139, lng: 77.2090 },
  'beijing': { lat: 39.9042, lng: 116.4074 },
  'shanghai': { lat: 31.2304, lng: 121.4737 },
  'manila': { lat: 14.5995, lng: 120.9842 },
  'ho chi minh': { lat: 10.8231, lng: 106.6297 },
  'taipei': { lat: 25.0330, lng: 121.5654 },
  'dubai': { lat: 25.2048, lng: 55.2708 },
  'istanbul': { lat: 41.0082, lng: 28.9784 },
  'doha': { lat: 25.2854, lng: 51.5310 },
  
  // USA
  'new york': { lat: 40.7128, lng: -74.0060 },
  'nyc': { lat: 40.7128, lng: -74.0060 },
  'los angeles': { lat: 34.0522, lng: -118.2437 },
  'la': { lat: 34.0522, lng: -118.2437 },
  'san francisco': { lat: 37.7749, lng: -122.4194 },
  'sf': { lat: 37.7749, lng: -122.4194 },
  'chicago': { lat: 41.8781, lng: -87.6298 },
  'houston': { lat: 29.7604, lng: -95.3698 },
  'mía': { lat: 25.7617, lng: -80.1918 },
  'miami': { lat: 25.7617, lng: -80.1918 },
  'seattle': { lat: 47.6062, lng: -122.3321 },
  
  // Europe
  'paris': { lat: 48.8566, lng: 2.3522 },
  'berlin': { lat: 52.5200, lng: 13.4050 },
  'amsterdam': { lat: 52.3676, lng: 4.9041 },
  'madrid': { lat: 40.4168, lng: -3.7038 },
  'rome': { lat: 41.9028, lng: 12.4964 },
  'zurich': { lat: 47.3769, lng: 8.5417 },
  
  // Australia/NZ
  'sydney': { lat: -33.8688, lng: 151.2093 },
  'melbourne': { lat: -37.8136, lng: 144.9631 },
  'perth': { lat: -31.9505, lng: 115.8605 },
  'auckland': { lat: -36.8485, lng: 174.7633 },
};

export const getCoordinatesForCity = (city: string) => {
    if (!city) return null;
    const key = city.toLowerCase().trim();
    if (CITY_COORDINATES[key]) return CITY_COORDINATES[key];
    // Partial match attempt
    const found = Object.keys(CITY_COORDINATES).find(k => key.includes(k) || k.includes(key));
    return found ? CITY_COORDINATES[found] : null;
};

export const calculateDistance = (lat1: number, lon1: number, lat2: number, lon2: number) => {
  const R = 6371; // Radius of earth in km
  const dLat = (lat2 - lat1) * (Math.PI / 180);
  const dLon = (lon2 - lon1) * (Math.PI / 180);
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(lat1 * (Math.PI / 180)) * Math.cos(lat2 * (Math.PI / 180)) *
    Math.sin(dLon / 2) * Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  const d = R * c; 
  return d; // Return precise float
};

export const HOSPITALS: Hospital[] = [
  // ==================== THAILAND ====================
  {
    id: '1',
    name: 'Bumrungrad International Hospital',
    location: 'Bangkok',
    country: 'Thailand',
    coordinates: { lat: 13.7463, lng: 100.5525 },
    specialties: ['Cardiology', 'Orthopedics', 'Oncology', 'Check-up'],
    rating: 4.9,
    reviewCount: 1250,
    imageUrl: 'https://picsum.photos/800/600?random=1',
    images: [
      'https://picsum.photos/800/600?random=1',
      'https://picsum.photos/800/600?random=101',
      'https://picsum.photos/800/600?random=102',
      'https://picsum.photos/800/600?random=103',
      'https://picsum.photos/800/600?random=104',
    ],
    priceRange: '$$$',
    description: 'World-class multi-specialty hospital known for medical tourism and advanced technology.',
    accreditation: ['JCI', 'GHA'],
  },
  {
    id: '2',
    name: 'Bangkok Hospital',
    location: 'Bangkok',
    country: 'Thailand',
    coordinates: { lat: 13.7490, lng: 100.5835 },
    specialties: ['Cardiology', 'Orthopedics', 'Neurology'],
    rating: 4.7,
    reviewCount: 1450,
    imageUrl: 'https://picsum.photos/800/600?random=2',
    images: ['https://picsum.photos/800/600?random=2', 'https://picsum.photos/800/600?random=201'],
    priceRange: '$$$',
    description: 'Flagship of the Bangkok Dusit Medical Services, offering specialized heart and cancer centers.',
    accreditation: ['JCI'],
  },
  {
    id: '3',
    name: 'Samitivej Sukhumvit Hospital',
    location: 'Bangkok',
    country: 'Thailand',
    coordinates: { lat: 13.7371, lng: 100.5746 },
    specialties: ['Pediatrics', 'Cardiology', 'Wellness'],
    rating: 4.8,
    reviewCount: 1100,
    imageUrl: 'https://picsum.photos/800/600?random=3',
    images: ['https://picsum.photos/800/600?random=3', 'https://picsum.photos/800/600?random=301'],
    priceRange: '$$$',
    description: 'Award-winning hospital known for its pediatric care and comprehensive wellness programs.',
    accreditation: ['JCI'],
  },
  {
    id: '4',
    name: 'Vejthani Hospital',
    location: 'Bangkok',
    country: 'Thailand',
    coordinates: { lat: 13.7649, lng: 100.6137 },
    specialties: ['Orthopedics', 'Spine Surgery', 'Oncology', 'Fertility'],
    rating: 4.6,
    reviewCount: 890,
    imageUrl: 'https://picsum.photos/800/600?random=4',
    images: ['https://picsum.photos/800/600?random=4', 'https://picsum.photos/800/600?random=401'],
    priceRange: '$$',
    description: 'International hospital specializing in orthopedic and spine treatments with global patient services.',
    accreditation: ['JCI', 'GHA'],
  },
  {
    id: '5',
    name: 'Phyathai 2 Hospital',
    location: 'Bangkok',
    country: 'Thailand',
    coordinates: { lat: 13.7784, lng: 100.5420 },
    specialties: ['Cardiology', 'Neurology', 'Gastroenterology'],
    rating: 4.5,
    reviewCount: 720,
    imageUrl: 'https://picsum.photos/800/600?random=5',
    images: ['https://picsum.photos/800/600?random=5', 'https://picsum.photos/800/600?random=501'],
    priceRange: '$$',
    description: 'Part of the Paolo-Phyathai hospital group offering comprehensive medical services.',
    accreditation: ['JCI'],
  },
  {
    id: '6',
    name: 'BNH Hospital',
    location: 'Bangkok',
    country: 'Thailand',
    coordinates: { lat: 13.7285, lng: 100.5389 },
    specialties: ['Fertility', 'Maternity', 'Orthopedics', 'Wellness'],
    rating: 4.7,
    reviewCount: 650,
    imageUrl: 'https://picsum.photos/800/600?random=6',
    images: ['https://picsum.photos/800/600?random=6', 'https://picsum.photos/800/600?random=601'],
    priceRange: '$$$',
    description: 'Historic hospital established in 1898, known for IVF and maternity services.',
    accreditation: ['JCI'],
  },
  {
    id: '7',
    name: 'Praram 9 Hospital',
    location: 'Bangkok',
    country: 'Thailand',
    coordinates: { lat: 13.7573, lng: 100.5659 },
    specialties: ['Cardiology', 'Oncology', 'Urology'],
    rating: 4.5,
    reviewCount: 540,
    imageUrl: 'https://picsum.photos/800/600?random=7',
    images: ['https://picsum.photos/800/600?random=7', 'https://picsum.photos/800/600?random=701'],
    priceRange: '$$',
    description: 'Modern hospital offering advanced cardiac and cancer treatment facilities.',
    accreditation: ['HA Thailand'],
  },
  {
    id: '8',
    name: 'Samitivej Srinakarin Hospital',
    location: 'Bangkok',
    country: 'Thailand',
    coordinates: { lat: 13.6512, lng: 100.6347 },
    specialties: ['Pediatrics', 'Cardiology', 'Orthopedics'],
    rating: 4.6,
    reviewCount: 480,
    imageUrl: 'https://picsum.photos/800/600?random=8',
    images: ['https://picsum.photos/800/600?random=8', 'https://picsum.photos/800/600?random=801'],
    priceRange: '$$$',
    description: 'Full-service hospital with specialized children and women health centers.',
    accreditation: ['JCI'],
  },
  {
    id: '9',
    name: 'Yanhee International Hospital',
    location: 'Bangkok',
    country: 'Thailand',
    coordinates: { lat: 13.7923, lng: 100.4567 },
    specialties: ['Cosmetic Surgery', 'Dermatology', 'Weight Loss', 'Wellness'],
    rating: 4.4,
    reviewCount: 1200,
    imageUrl: 'https://picsum.photos/800/600?random=9',
    images: ['https://picsum.photos/800/600?random=9', 'https://picsum.photos/800/600?random=901'],
    priceRange: '$$',
    description: 'Renowned for cosmetic and plastic surgery with international patient coordinators.',
    accreditation: ['JCI'],
  },
  {
    id: '10',
    name: 'Bangkok Hospital Phuket',
    location: 'Phuket',
    country: 'Thailand',
    coordinates: { lat: 7.9107, lng: 98.3693 },
    specialties: ['Emergency', 'Orthopedics', 'Cardiology', 'Hyperbaric Medicine'],
    rating: 4.6,
    reviewCount: 780,
    imageUrl: 'https://picsum.photos/800/600?random=10',
    images: ['https://picsum.photos/800/600?random=10', 'https://picsum.photos/800/600?random=1001'],
    priceRange: '$$$',
    description: 'Premier hospital in Phuket catering to tourists and expats with multilingual staff.',
    accreditation: ['JCI'],
  },
  {
    id: '11',
    name: 'Phuket International Hospital',
    location: 'Phuket',
    country: 'Thailand',
    coordinates: { lat: 7.8804, lng: 98.3923 },
    specialties: ['Emergency', 'General Surgery', 'Orthopedics'],
    rating: 4.4,
    reviewCount: 560,
    imageUrl: 'https://picsum.photos/800/600?random=11',
    images: ['https://picsum.photos/800/600?random=11', 'https://picsum.photos/800/600?random=1101'],
    priceRange: '$$',
    description: 'International standard hospital serving Phuket and surrounding islands.',
    accreditation: ['HA Thailand'],
  },
  {
    id: '12',
    name: 'Chiang Mai Ram Hospital',
    location: 'Chiang Mai',
    country: 'Thailand',
    coordinates: { lat: 18.7883, lng: 98.9853 },
    specialties: ['Cardiology', 'Orthopedics', 'Check-up', 'Wellness'],
    rating: 4.5,
    reviewCount: 620,
    imageUrl: 'https://picsum.photos/800/600?random=12',
    images: ['https://picsum.photos/800/600?random=12', 'https://picsum.photos/800/600?random=1201'],
    priceRange: '$$',
    description: 'Leading private hospital in Northern Thailand with comprehensive medical services.',
    accreditation: ['JCI'],
  },
  {
    id: '13',
    name: 'Bangkok Hospital Chiang Mai',
    location: 'Chiang Mai',
    country: 'Thailand',
    coordinates: { lat: 18.8126, lng: 98.9672 },
    specialties: ['Cardiology', 'Oncology', 'Neurology', 'Orthopedics'],
    rating: 4.6,
    reviewCount: 540,
    imageUrl: 'https://picsum.photos/800/600?random=13',
    images: ['https://picsum.photos/800/600?random=13', 'https://picsum.photos/800/600?random=1301'],
    priceRange: '$$$',
    description: 'Part of BDMS network offering advanced medical care in Northern Thailand.',
    accreditation: ['JCI'],
  },
  {
    id: '14',
    name: 'Bangkok Hospital Pattaya',
    location: 'Pattaya',
    country: 'Thailand',
    coordinates: { lat: 12.9236, lng: 100.8825 },
    specialties: ['Cardiology', 'Orthopedics', 'Emergency', 'Gastroenterology'],
    rating: 4.5,
    reviewCount: 680,
    imageUrl: 'https://picsum.photos/800/600?random=14',
    images: ['https://picsum.photos/800/600?random=14', 'https://picsum.photos/800/600?random=1401'],
    priceRange: '$$$',
    description: 'International hospital serving the Eastern Seaboard with 24/7 emergency services.',
    accreditation: ['JCI'],
  },
  {
    id: '15',
    name: 'Pattaya International Hospital',
    location: 'Pattaya',
    country: 'Thailand',
    coordinates: { lat: 12.9456, lng: 100.8912 },
    specialties: ['Emergency', 'General Surgery', 'Orthopedics'],
    rating: 4.3,
    reviewCount: 420,
    imageUrl: 'https://picsum.photos/800/600?random=15',
    images: ['https://picsum.photos/800/600?random=15', 'https://picsum.photos/800/600?random=1501'],
    priceRange: '$$',
    description: 'Multi-specialty hospital with interpreters for international patients.',
    accreditation: ['HA Thailand'],
  },
  {
    id: '16',
    name: 'Bangkok Hospital Samui',
    location: 'Koh Samui',
    country: 'Thailand',
    coordinates: { lat: 9.5120, lng: 100.0627 },
    specialties: ['Emergency', 'Hyperbaric Medicine', 'Orthopedics'],
    rating: 4.4,
    reviewCount: 380,
    imageUrl: 'https://picsum.photos/800/600?random=16',
    images: ['https://picsum.photos/800/600?random=16', 'https://picsum.photos/800/600?random=1601'],
    priceRange: '$$$',
    description: 'Premier healthcare facility on Koh Samui island with diving medicine specialty.',
    accreditation: ['JCI'],
  },
  {
    id: '17',
    name: 'Bangkok Hospital Hua Hin',
    location: 'Hua Hin',
    country: 'Thailand',
    coordinates: { lat: 12.5684, lng: 99.9576 },
    specialties: ['Cardiology', 'Orthopedics', 'Check-up', 'Wellness'],
    rating: 4.5,
    reviewCount: 340,
    imageUrl: 'https://picsum.photos/800/600?random=17',
    images: ['https://picsum.photos/800/600?random=17', 'https://picsum.photos/800/600?random=1701'],
    priceRange: '$$$',
    description: 'Modern hospital serving the resort town with international standard care.',
    accreditation: ['JCI'],
  },
  {
    id: '18',
    name: 'Sikarin Hospital',
    location: 'Bangkok',
    country: 'Thailand',
    coordinates: { lat: 13.6789, lng: 100.6123 },
    specialties: ['Maternity', 'Pediatrics', 'Fertility', 'General Surgery'],
    rating: 4.4,
    reviewCount: 520,
    imageUrl: 'https://picsum.photos/800/600?random=18',
    images: ['https://picsum.photos/800/600?random=18', 'https://picsum.photos/800/600?random=1801'],
    priceRange: '$$',
    description: 'Family-focused hospital with excellent maternity and pediatric departments.',
    accreditation: ['HA Thailand'],
  },
  {
    id: '19',
    name: 'Paolo Memorial Hospital Chokchai 4',
    location: 'Bangkok',
    country: 'Thailand',
    coordinates: { lat: 13.7912, lng: 100.5834 },
    specialties: ['General Medicine', 'Cardiology', 'Orthopedics'],
    rating: 4.3,
    reviewCount: 410,
    imageUrl: 'https://picsum.photos/800/600?random=19',
    images: ['https://picsum.photos/800/600?random=19', 'https://picsum.photos/800/600?random=1901'],
    priceRange: '$$',
    description: 'Community hospital offering affordable quality healthcare.',
    accreditation: ['HA Thailand'],
  },
  {
    id: '20',
    name: 'Thonburi Hospital',
    location: 'Bangkok',
    country: 'Thailand',
    coordinates: { lat: 13.7234, lng: 100.4789 },
    specialties: ['Cardiology', 'Neurology', 'Oncology', 'Orthopedics'],
    rating: 4.5,
    reviewCount: 580,
    imageUrl: 'https://picsum.photos/800/600?random=20',
    images: ['https://picsum.photos/800/600?random=20', 'https://picsum.photos/800/600?random=2001'],
    priceRange: '$$',
    description: 'Established hospital on the Thonburi side with comprehensive specialist services.',
    accreditation: ['JCI'],
  },

  // ==================== SINGAPORE ====================
  {
    id: '21',
    name: 'Mount Elizabeth Hospital',
    location: 'Orchard',
    country: 'Singapore',
    coordinates: { lat: 1.3048, lng: 103.8353 },
    specialties: ['Neurology', 'Cardiology', 'Oncology'],
    rating: 4.8,
    reviewCount: 980,
    imageUrl: 'https://picsum.photos/800/600?random=21',
    images: ['https://picsum.photos/800/600?random=21', 'https://picsum.photos/800/600?random=2101'],
    priceRange: '$$$$',
    description: 'Premier private hospital in Asia, renowned for its depth of expertise in complex surgeries.',
    accreditation: ['JCI'],
  },
  {
    id: '22',
    name: 'Gleneagles Hospital',
    location: 'Napier',
    country: 'Singapore',
    coordinates: { lat: 1.3069, lng: 103.8198 },
    specialties: ['Cardiology', 'Transplant', 'Orthopedics'],
    rating: 4.7,
    reviewCount: 950,
    imageUrl: 'https://picsum.photos/800/600?random=22',
    images: ['https://picsum.photos/800/600?random=22', 'https://picsum.photos/800/600?random=2201'],
    priceRange: '$$$$',
    description: 'Private hospital providing a wide range of medical and surgical services.',
    accreditation: ['JCI'],
  },
  {
    id: '23',
    name: 'Farrer Park Hospital',
    location: 'Farrer Park',
    country: 'Singapore',
    coordinates: { lat: 1.3122, lng: 103.8546 },
    specialties: ['Cardiology', 'Orthopedics', 'Gastroenterology'],
    rating: 4.7,
    reviewCount: 650,
    imageUrl: 'https://picsum.photos/800/600?random=23',
    images: ['https://picsum.photos/800/600?random=23', 'https://picsum.photos/800/600?random=2301'],
    priceRange: '$$$$',
    description: 'A private tertiary healthcare institute designed for patients seeking comfort and premium care.',
    accreditation: ['JCI'],
  },
  {
    id: '24',
    name: 'Raffles Hospital',
    location: 'Bugis',
    country: 'Singapore',
    coordinates: { lat: 1.3009, lng: 103.8584 },
    specialties: ['Cardiology', 'Oncology', 'Traditional Chinese Medicine'],
    rating: 4.6,
    reviewCount: 920,
    imageUrl: 'https://picsum.photos/800/600?random=24',
    images: ['https://picsum.photos/800/600?random=24', 'https://picsum.photos/800/600?random=2401'],
    priceRange: '$$$',
    description: 'Flagship hospital of the Raffles Medical Group, located in the heart of Singapore.',
    accreditation: ['JCI'],
  },
  {
    id: '25',
    name: 'Mount Elizabeth Novena Hospital',
    location: 'Novena',
    country: 'Singapore',
    coordinates: { lat: 1.3204, lng: 103.8437 },
    specialties: ['Oncology', 'Cardiology', 'Neurology', 'Robotic Surgery'],
    rating: 4.8,
    reviewCount: 720,
    imageUrl: 'https://picsum.photos/800/600?random=25',
    images: ['https://picsum.photos/800/600?random=25', 'https://picsum.photos/800/600?random=2501'],
    priceRange: '$$$$',
    description: 'State-of-the-art hospital with advanced surgical technologies and specialist centers.',
    accreditation: ['JCI'],
  },
  {
    id: '26',
    name: 'Parkway East Hospital',
    location: 'East Coast',
    country: 'Singapore',
    coordinates: { lat: 1.3156, lng: 103.9134 },
    specialties: ['Maternity', 'Pediatrics', 'General Surgery', 'Orthopedics'],
    rating: 4.5,
    reviewCount: 540,
    imageUrl: 'https://picsum.photos/800/600?random=26',
    images: ['https://picsum.photos/800/600?random=26', 'https://picsum.photos/800/600?random=2601'],
    priceRange: '$$$',
    description: 'Community hospital in the east with focus on family healthcare.',
    accreditation: ['JCI'],
  },
  {
    id: '27',
    name: 'Thomson Medical Centre',
    location: 'Novena',
    country: 'Singapore',
    coordinates: { lat: 1.3198, lng: 103.8412 },
    specialties: ['Maternity', 'Fertility', 'Pediatrics', 'Women Health'],
    rating: 4.7,
    reviewCount: 890,
    imageUrl: 'https://picsum.photos/800/600?random=27',
    images: ['https://picsum.photos/800/600?random=27', 'https://picsum.photos/800/600?random=2701'],
    priceRange: '$$$',
    description: 'Leading private hospital for women and children healthcare in Singapore.',
    accreditation: ['JCI'],
  },
  {
    id: '28',
    name: 'Singapore General Hospital',
    location: 'Outram',
    country: 'Singapore',
    coordinates: { lat: 1.2789, lng: 103.8356 },
    specialties: ['Transplant', 'Oncology', 'Cardiology', 'Neurology'],
    rating: 4.8,
    reviewCount: 2100,
    imageUrl: 'https://picsum.photos/800/600?random=28',
    images: ['https://picsum.photos/800/600?random=28', 'https://picsum.photos/800/600?random=2801'],
    priceRange: '$$',
    description: 'Largest and oldest hospital in Singapore, a tertiary referral center for complex cases.',
    accreditation: ['JCI'],
  },
  {
    id: '29',
    name: 'National University Hospital',
    location: 'Kent Ridge',
    country: 'Singapore',
    coordinates: { lat: 1.2936, lng: 103.7830 },
    specialties: ['Oncology', 'Cardiology', 'Neurology', 'Research'],
    rating: 4.7,
    reviewCount: 1850,
    imageUrl: 'https://picsum.photos/800/600?random=29',
    images: ['https://picsum.photos/800/600?random=29', 'https://picsum.photos/800/600?random=2901'],
    priceRange: '$$',
    description: 'Academic medical center affiliated with the National University of Singapore.',
    accreditation: ['JCI'],
  },
  {
    id: '30',
    name: 'Tan Tock Seng Hospital',
    location: 'Novena',
    country: 'Singapore',
    coordinates: { lat: 1.3215, lng: 103.8467 },
    specialties: ['Rehabilitation', 'Infectious Disease', 'Geriatrics', 'Neurology'],
    rating: 4.6,
    reviewCount: 1620,
    imageUrl: 'https://picsum.photos/800/600?random=30',
    images: ['https://picsum.photos/800/600?random=30', 'https://picsum.photos/800/600?random=3001'],
    priceRange: '$$',
    description: 'Second largest acute care hospital with national centers for infectious diseases.',
    accreditation: ['JCI'],
  },
  {
    id: '31',
    name: 'KK Women\'s and Children\'s Hospital',
    location: 'Bukit Timah',
    country: 'Singapore',
    coordinates: { lat: 1.3112, lng: 103.8456 },
    specialties: ['Maternity', 'Pediatrics', 'Gynecology', 'Neonatology'],
    rating: 4.8,
    reviewCount: 1450,
    imageUrl: 'https://picsum.photos/800/600?random=31',
    images: ['https://picsum.photos/800/600?random=31', 'https://picsum.photos/800/600?random=3101'],
    priceRange: '$$',
    description: 'Largest specialist center for women and children in Singapore.',
    accreditation: ['JCI'],
  },
  {
    id: '32',
    name: 'National Heart Centre Singapore',
    location: 'Outram',
    country: 'Singapore',
    coordinates: { lat: 1.2794, lng: 103.8378 },
    specialties: ['Cardiology', 'Cardiac Surgery', 'Heart Transplant'],
    rating: 4.9,
    reviewCount: 980,
    imageUrl: 'https://picsum.photos/800/600?random=32',
    images: ['https://picsum.photos/800/600?random=32', 'https://picsum.photos/800/600?random=3201'],
    priceRange: '$$$',
    description: 'National referral center for cardiovascular diseases with research excellence.',
    accreditation: ['JCI'],
  },
  {
    id: '33',
    name: 'National Cancer Centre Singapore',
    location: 'Outram',
    country: 'Singapore',
    coordinates: { lat: 1.2801, lng: 103.8367 },
    specialties: ['Oncology', 'Radiation Therapy', 'Surgical Oncology'],
    rating: 4.8,
    reviewCount: 870,
    imageUrl: 'https://picsum.photos/800/600?random=33',
    images: ['https://picsum.photos/800/600?random=33', 'https://picsum.photos/800/600?random=3301'],
    priceRange: '$$$',
    description: 'Leading cancer center in Asia with comprehensive oncology services.',
    accreditation: ['JCI'],
  },

  // ==================== MALAYSIA ====================
  {
    id: '34',
    name: 'Sunway Medical Centre',
    location: 'Kuala Lumpur',
    country: 'Malaysia',
    coordinates: { lat: 3.0684, lng: 101.6044 },
    specialties: ['Fertility', 'Orthopedics', 'Pediatrics'],
    rating: 4.7,
    reviewCount: 850,
    imageUrl: 'https://picsum.photos/800/600?random=34',
    images: ['https://picsum.photos/800/600?random=34', 'https://picsum.photos/800/600?random=3401'],
    priceRange: '$$',
    description: 'Leading private quaternary hospital in Malaysia offering comprehensive medical services.',
    accreditation: ['ACHS', 'MSQH'],
  },
  {
    id: '35',
    name: 'Prince Court Medical Centre',
    location: 'Kuala Lumpur',
    country: 'Malaysia',
    coordinates: { lat: 3.1495, lng: 101.7208 },
    specialties: ['Cardiology', 'Oncology', 'Orthopedics'],
    rating: 4.8,
    reviewCount: 1100,
    imageUrl: 'https://picsum.photos/800/600?random=35',
    images: ['https://picsum.photos/800/600?random=35', 'https://picsum.photos/800/600?random=3501'],
    priceRange: '$$$',
    description: 'A luxurious private hospital offering premium care and personalized medical services.',
    accreditation: ['MTQUA', 'MSQH'],
  },
  {
    id: '36',
    name: 'Pantai Hospital Kuala Lumpur',
    location: 'Kuala Lumpur',
    country: 'Malaysia',
    coordinates: { lat: 3.1077, lng: 101.6669 },
    specialties: ['Cardiology', 'Oncology', 'Neurosurgery'],
    rating: 4.6,
    reviewCount: 800,
    imageUrl: 'https://picsum.photos/800/600?random=36',
    images: ['https://picsum.photos/800/600?random=36', 'https://picsum.photos/800/600?random=3601'],
    priceRange: '$$',
    description: 'A premier private hospital in KL with a dedicated Heart Centre and Cancer Centre.',
    accreditation: ['JCI', 'MSQH'],
  },
  {
    id: '37',
    name: 'Penang Adventist Hospital',
    location: 'Penang',
    country: 'Malaysia',
    coordinates: { lat: 5.4307, lng: 100.3025 },
    specialties: ['Cardiology', 'Oncology', 'Wellness'],
    rating: 4.6,
    reviewCount: 700,
    imageUrl: 'https://picsum.photos/800/600?random=37',
    images: ['https://picsum.photos/800/600?random=37', 'https://picsum.photos/800/600?random=3701'],
    priceRange: '$$',
    description: 'Not-for-profit hospital known for heart health and wellness programs.',
    accreditation: ['JCI', 'MSQH'],
  },
  {
    id: '38',
    name: 'Gleneagles Penang',
    location: 'Penang',
    country: 'Malaysia',
    coordinates: { lat: 5.4412, lng: 100.3067 },
    specialties: ['Cardiology', 'Oncology', 'Neurology', 'Orthopedics'],
    rating: 4.7,
    reviewCount: 920,
    imageUrl: 'https://picsum.photos/800/600?random=38',
    images: ['https://picsum.photos/800/600?random=38', 'https://picsum.photos/800/600?random=3801'],
    priceRange: '$$$',
    description: 'Part of IHH Healthcare group with comprehensive medical tourism services.',
    accreditation: ['JCI', 'MSQH'],
  },
  {
    id: '39',
    name: 'Island Hospital Penang',
    location: 'Penang',
    country: 'Malaysia',
    coordinates: { lat: 5.4156, lng: 100.3234 },
    specialties: ['Orthopedics', 'Cardiology', 'Fertility', 'Oncology'],
    rating: 4.6,
    reviewCount: 780,
    imageUrl: 'https://picsum.photos/800/600?random=39',
    images: ['https://picsum.photos/800/600?random=39', 'https://picsum.photos/800/600?random=3901'],
    priceRange: '$$',
    description: 'Leading private hospital in Penang with specialized centers and medical tourism focus.',
    accreditation: ['JCI', 'MSQH'],
  },
  {
    id: '40',
    name: 'Subang Jaya Medical Centre',
    location: 'Subang Jaya',
    country: 'Malaysia',
    coordinates: { lat: 3.0523, lng: 101.5867 },
    specialties: ['Cardiology', 'Orthopedics', 'Oncology', 'Neurology'],
    rating: 4.6,
    reviewCount: 680,
    imageUrl: 'https://picsum.photos/800/600?random=40',
    images: ['https://picsum.photos/800/600?random=40', 'https://picsum.photos/800/600?random=4001'],
    priceRange: '$$',
    description: 'Tertiary care hospital with strong cardiac and orthopedic programs.',
    accreditation: ['MSQH'],
  },
  {
    id: '41',
    name: 'Gleneagles Kuala Lumpur',
    location: 'Kuala Lumpur',
    country: 'Malaysia',
    coordinates: { lat: 3.1567, lng: 101.7189 },
    specialties: ['Cardiology', 'Oncology', 'Neurology', 'Gastroenterology'],
    rating: 4.7,
    reviewCount: 890,
    imageUrl: 'https://picsum.photos/800/600?random=41',
    images: ['https://picsum.photos/800/600?random=41', 'https://picsum.photos/800/600?random=4101'],
    priceRange: '$$$',
    description: 'Premier private hospital with international patient services and specialist centers.',
    accreditation: ['JCI', 'MSQH'],
  },
  {
    id: '42',
    name: 'KPJ Damansara Specialist Hospital',
    location: 'Petaling Jaya',
    country: 'Malaysia',
    coordinates: { lat: 3.1234, lng: 101.6234 },
    specialties: ['Cardiology', 'Orthopedics', 'Urology', 'Women Health'],
    rating: 4.5,
    reviewCount: 620,
    imageUrl: 'https://picsum.photos/800/600?random=42',
    images: ['https://picsum.photos/800/600?random=42', 'https://picsum.photos/800/600?random=4201'],
    priceRange: '$$',
    description: 'Part of KPJ Healthcare group with comprehensive specialist services.',
    accreditation: ['MSQH'],
  },
  {
    id: '43',
    name: 'Columbia Asia Hospital Petaling Jaya',
    location: 'Petaling Jaya',
    country: 'Malaysia',
    coordinates: { lat: 3.1089, lng: 101.6412 },
    specialties: ['General Medicine', 'Orthopedics', 'Cardiology'],
    rating: 4.4,
    reviewCount: 480,
    imageUrl: 'https://picsum.photos/800/600?random=43',
    images: ['https://picsum.photos/800/600?random=43', 'https://picsum.photos/800/600?random=4301'],
    priceRange: '$$',
    description: 'Modern community hospital with affordable quality healthcare.',
    accreditation: ['MSQH'],
  },
  {
    id: '44',
    name: 'Tropicana Medical Centre',
    location: 'Petaling Jaya',
    country: 'Malaysia',
    coordinates: { lat: 3.1345, lng: 101.5923 },
    specialties: ['Cardiology', 'Oncology', 'Orthopedics', 'Check-up'],
    rating: 4.5,
    reviewCount: 520,
    imageUrl: 'https://picsum.photos/800/600?random=44',
    images: ['https://picsum.photos/800/600?random=44', 'https://picsum.photos/800/600?random=4401'],
    priceRange: '$$',
    description: 'Multi-specialty hospital with focus on patient comfort and quality care.',
    accreditation: ['MSQH'],
  },
  {
    id: '45',
    name: 'KPJ Johor Specialist Hospital',
    location: 'Johor Bahru',
    country: 'Malaysia',
    coordinates: { lat: 1.4712, lng: 103.7612 },
    specialties: ['Cardiology', 'Orthopedics', 'Oncology', 'Fertility'],
    rating: 4.5,
    reviewCount: 580,
    imageUrl: 'https://picsum.photos/800/600?random=45',
    images: ['https://picsum.photos/800/600?random=45', 'https://picsum.photos/800/600?random=4501'],
    priceRange: '$$',
    description: 'Leading private hospital in Johor serving patients from Malaysia and Singapore.',
    accreditation: ['MSQH'],
  },
  {
    id: '46',
    name: 'Gleneagles Medini',
    location: 'Johor Bahru',
    country: 'Malaysia',
    coordinates: { lat: 1.4234, lng: 103.6234 },
    specialties: ['Cardiology', 'Oncology', 'Orthopedics', 'Neurology'],
    rating: 4.6,
    reviewCount: 450,
    imageUrl: 'https://picsum.photos/800/600?random=46',
    images: ['https://picsum.photos/800/600?random=46', 'https://picsum.photos/800/600?random=4601'],
    priceRange: '$$$',
    description: 'Modern hospital in Iskandar Puteri with premium healthcare services.',
    accreditation: ['JCI', 'MSQH'],
  },
  {
    id: '47',
    name: 'Mahkota Medical Centre',
    location: 'Malacca',
    country: 'Malaysia',
    coordinates: { lat: 2.1912, lng: 102.2512 },
    specialties: ['Cardiology', 'Orthopedics', 'Oncology', 'Check-up'],
    rating: 4.5,
    reviewCount: 720,
    imageUrl: 'https://picsum.photos/800/600?random=47',
    images: ['https://picsum.photos/800/600?random=47', 'https://picsum.photos/800/600?random=4701'],
    priceRange: '$$',
    description: 'Premier medical tourism destination in Malacca with comprehensive services.',
    accreditation: ['JCI', 'MSQH'],
  },
  {
    id: '48',
    name: 'Oriental Melaka Straits Medical Centre',
    location: 'Malacca',
    country: 'Malaysia',
    coordinates: { lat: 2.2034, lng: 102.2678 },
    specialties: ['Cardiology', 'Orthopedics', 'General Surgery'],
    rating: 4.4,
    reviewCount: 420,
    imageUrl: 'https://picsum.photos/800/600?random=48',
    images: ['https://picsum.photos/800/600?random=48', 'https://picsum.photos/800/600?random=4801'],
    priceRange: '$$',
    description: 'Modern hospital serving Malacca region with quality specialist care.',
    accreditation: ['MSQH'],
  },
  {
    id: '49',
    name: 'Hospital Fatimah',
    location: 'Ipoh',
    country: 'Malaysia',
    coordinates: { lat: 4.5934, lng: 101.0789 },
    specialties: ['Cardiology', 'Orthopedics', 'Oncology', 'Pediatrics'],
    rating: 4.5,
    reviewCount: 540,
    imageUrl: 'https://picsum.photos/800/600?random=49',
    images: ['https://picsum.photos/800/600?random=49', 'https://picsum.photos/800/600?random=4901'],
    priceRange: '$$',
    description: 'Established private hospital in Perak with comprehensive medical services.',
    accreditation: ['MSQH'],
  },
  {
    id: '50',
    name: 'KPJ Ipoh Specialist Hospital',
    location: 'Ipoh',
    country: 'Malaysia',
    coordinates: { lat: 4.6012, lng: 101.0923 },
    specialties: ['Cardiology', 'Orthopedics', 'Neurology', 'Gastroenterology'],
    rating: 4.4,
    reviewCount: 480,
    imageUrl: 'https://picsum.photos/800/600?random=50',
    images: ['https://picsum.photos/800/600?random=50', 'https://picsum.photos/800/600?random=5001'],
    priceRange: '$$',
    description: 'Part of KPJ Healthcare network serving Northern Perak region.',
    accreditation: ['MSQH'],
  },
  {
    id: '51',
    name: 'Sabah Medical Centre',
    location: 'Kota Kinabalu',
    country: 'Malaysia',
    coordinates: { lat: 5.9734, lng: 116.0723 },
    specialties: ['Cardiology', 'Orthopedics', 'Oncology', 'Pediatrics'],
    rating: 4.5,
    reviewCount: 420,
    imageUrl: 'https://picsum.photos/800/600?random=51',
    images: ['https://picsum.photos/800/600?random=51', 'https://picsum.photos/800/600?random=5101'],
    priceRange: '$$',
    description: 'Premier private hospital in Sabah with comprehensive healthcare services.',
    accreditation: ['MSQH'],
  },
  {
    id: '52',
    name: 'Gleneagles Kota Kinabalu',
    location: 'Kota Kinabalu',
    country: 'Malaysia',
    coordinates: { lat: 5.9812, lng: 116.0834 },
    specialties: ['Cardiology', 'Oncology', 'Orthopedics', 'Check-up'],
    rating: 4.6,
    reviewCount: 380,
    imageUrl: 'https://picsum.photos/800/600?random=52',
    images: ['https://picsum.photos/800/600?random=52', 'https://picsum.photos/800/600?random=5201'],
    priceRange: '$$$',
    description: 'International standard hospital in East Malaysia with specialist services.',
    accreditation: ['JCI', 'MSQH'],
  },
  {
    id: '53',
    name: 'Normah Medical Specialist Centre',
    location: 'Kuching',
    country: 'Malaysia',
    coordinates: { lat: 1.5423, lng: 110.3534 },
    specialties: ['Cardiology', 'Orthopedics', 'Oncology', 'Fertility'],
    rating: 4.5,
    reviewCount: 360,
    imageUrl: 'https://picsum.photos/800/600?random=53',
    images: ['https://picsum.photos/800/600?random=53', 'https://picsum.photos/800/600?random=5301'],
    priceRange: '$$',
    description: 'Leading private hospital in Sarawak with modern medical facilities.',
    accreditation: ['MSQH'],
  },

  // ==================== INDONESIA ====================
  {
    id: '54',
    name: 'Siloam Hospitals Lippo Village',
    location: 'Tangerang',
    country: 'Indonesia',
    coordinates: { lat: -6.2267, lng: 106.6079 },
    specialties: ['Cardiology', 'Neurology', 'Orthopedics'],
    rating: 4.6,
    reviewCount: 2100,
    imageUrl: 'https://picsum.photos/800/600?random=54',
    images: ['https://picsum.photos/800/600?random=54', 'https://picsum.photos/800/600?random=5401'],
    priceRange: '$$',
    description: 'First JCI accredited hospital in Indonesia, specializing in neuroscience and cardiology.',
    accreditation: ['JCI', 'KARS'],
  },
  {
    id: '55',
    name: 'RSU Bunda Jakarta',
    location: 'Jakarta',
    country: 'Indonesia',
    coordinates: { lat: -6.1908, lng: 106.8396 },
    specialties: ['Fertility', 'Maternity', 'Pediatrics'],
    rating: 4.7,
    reviewCount: 1500,
    imageUrl: 'https://picsum.photos/800/600?random=55',
    images: ['https://picsum.photos/800/600?random=55', 'https://picsum.photos/800/600?random=5501'],
    priceRange: '$$',
    description: 'A leading hospital in Jakarta focusing on mother and child care and fertility technologies.',
    accreditation: ['KARS'],
  },
  {
    id: '56',
    name: 'RS Pondok Indah',
    location: 'Jakarta',
    country: 'Indonesia',
    coordinates: { lat: -6.2678, lng: 106.7834 },
    specialties: ['Cardiology', 'Oncology', 'Orthopedics', 'Neurology'],
    rating: 4.7,
    reviewCount: 1800,
    imageUrl: 'https://picsum.photos/800/600?random=56',
    images: ['https://picsum.photos/800/600?random=56', 'https://picsum.photos/800/600?random=5601'],
    priceRange: '$$$',
    description: 'Premium private hospital group with international standard healthcare services.',
    accreditation: ['JCI', 'KARS'],
  },
  {
    id: '57',
    name: 'Siloam Hospitals Semanggi',
    location: 'Jakarta',
    country: 'Indonesia',
    coordinates: { lat: -6.2234, lng: 106.8123 },
    specialties: ['Cardiology', 'Neurology', 'Transplant', 'Oncology'],
    rating: 4.6,
    reviewCount: 1450,
    imageUrl: 'https://picsum.photos/800/600?random=57',
    images: ['https://picsum.photos/800/600?random=57', 'https://picsum.photos/800/600?random=5701'],
    priceRange: '$$',
    description: 'Flagship hospital of Siloam group with comprehensive specialist services.',
    accreditation: ['JCI', 'KARS'],
  },
  {
    id: '58',
    name: 'RS Medistra',
    location: 'Jakarta',
    country: 'Indonesia',
    coordinates: { lat: -6.2412, lng: 106.8234 },
    specialties: ['Cardiology', 'Orthopedics', 'Oncology', 'Urology'],
    rating: 4.5,
    reviewCount: 980,
    imageUrl: 'https://picsum.photos/800/600?random=58',
    images: ['https://picsum.photos/800/600?random=58', 'https://picsum.photos/800/600?random=5801'],
    priceRange: '$$$',
    description: 'Established private hospital known for cardiac and orthopedic excellence.',
    accreditation: ['JCI', 'KARS'],
  },
  {
    id: '59',
    name: 'RS Premier Jatinegara',
    location: 'Jakarta',
    country: 'Indonesia',
    coordinates: { lat: -6.2156, lng: 106.8678 },
    specialties: ['Cardiology', 'Neurology', 'Orthopedics', 'Check-up'],
    rating: 4.4,
    reviewCount: 720,
    imageUrl: 'https://picsum.photos/800/600?random=59',
    images: ['https://picsum.photos/800/600?random=59', 'https://picsum.photos/800/600?random=5901'],
    priceRange: '$$',
    description: 'Modern hospital in East Jakarta with comprehensive healthcare services.',
    accreditation: ['JCI', 'KARS'],
  },
  {
    id: '60',
    name: 'RS Mitra Keluarga Kelapa Gading',
    location: 'Jakarta',
    country: 'Indonesia',
    coordinates: { lat: -6.1534, lng: 106.9012 },
    specialties: ['Cardiology', 'Orthopedics', 'Pediatrics', 'Oncology'],
    rating: 4.5,
    reviewCount: 890,
    imageUrl: 'https://picsum.photos/800/600?random=60',
    images: ['https://picsum.photos/800/600?random=60', 'https://picsum.photos/800/600?random=6001'],
    priceRange: '$$',
    description: 'Part of Mitra Keluarga network with family-focused healthcare.',
    accreditation: ['KARS'],
  },
  {
    id: '61',
    name: 'Mayapada Hospital Jakarta Selatan',
    location: 'Jakarta',
    country: 'Indonesia',
    coordinates: { lat: -6.2534, lng: 106.8123 },
    specialties: ['Cardiology', 'Neurology', 'Oncology', 'Orthopedics'],
    rating: 4.6,
    reviewCount: 650,
    imageUrl: 'https://picsum.photos/800/600?random=61',
    images: ['https://picsum.photos/800/600?random=61', 'https://picsum.photos/800/600?random=6101'],
    priceRange: '$$$',
    description: 'Modern tertiary hospital with advanced medical technology.',
    accreditation: ['JCI', 'KARS'],
  },
  {
    id: '62',
    name: 'RS Husada Utama',
    location: 'Surabaya',
    country: 'Indonesia',
    coordinates: { lat: -7.2575, lng: 112.7521 },
    specialties: ['Cardiology', 'Orthopedics', 'Oncology', 'Neurology'],
    rating: 4.5,
    reviewCount: 780,
    imageUrl: 'https://picsum.photos/800/600?random=62',
    images: ['https://picsum.photos/800/600?random=62', 'https://picsum.photos/800/600?random=6201'],
    priceRange: '$$',
    description: 'Leading private hospital in East Java with comprehensive services.',
    accreditation: ['KARS'],
  },
  {
    id: '63',
    name: 'Siloam Hospitals Surabaya',
    location: 'Surabaya',
    country: 'Indonesia',
    coordinates: { lat: -7.2689, lng: 112.7634 },
    specialties: ['Cardiology', 'Neurology', 'Orthopedics', 'Pediatrics'],
    rating: 4.5,
    reviewCount: 680,
    imageUrl: 'https://picsum.photos/800/600?random=63',
    images: ['https://picsum.photos/800/600?random=63', 'https://picsum.photos/800/600?random=6301'],
    priceRange: '$$',
    description: 'Part of Siloam network serving East Java region.',
    accreditation: ['JCI', 'KARS'],
  },
  {
    id: '64',
    name: 'RS Premier Surabaya',
    location: 'Surabaya',
    country: 'Indonesia',
    coordinates: { lat: -7.2512, lng: 112.7412 },
    specialties: ['Cardiology', 'Oncology', 'Orthopedics', 'Check-up'],
    rating: 4.4,
    reviewCount: 540,
    imageUrl: 'https://picsum.photos/800/600?random=64',
    images: ['https://picsum.photos/800/600?random=64', 'https://picsum.photos/800/600?random=6401'],
    priceRange: '$$',
    description: 'Modern hospital with executive health check programs.',
    accreditation: ['KARS'],
  },
  {
    id: '65',
    name: 'BIMC Hospital Kuta',
    location: 'Bali',
    country: 'Indonesia',
    coordinates: { lat: -8.7234, lng: 115.1723 },
    specialties: ['Emergency', 'Orthopedics', 'General Surgery', 'Hyperbaric Medicine'],
    rating: 4.6,
    reviewCount: 920,
    imageUrl: 'https://picsum.photos/800/600?random=65',
    images: ['https://picsum.photos/800/600?random=65', 'https://picsum.photos/800/600?random=6501'],
    priceRange: '$$$',
    description: 'International standard hospital in Bali serving tourists and expats.',
    accreditation: ['ACHSI', 'KARS'],
  },
  {
    id: '66',
    name: 'Siloam Hospitals Bali',
    location: 'Bali',
    country: 'Indonesia',
    coordinates: { lat: -8.6812, lng: 115.2123 },
    specialties: ['Cardiology', 'Orthopedics', 'Neurology', 'Emergency'],
    rating: 4.5,
    reviewCount: 680,
    imageUrl: 'https://picsum.photos/800/600?random=66',
    images: ['https://picsum.photos/800/600?random=66', 'https://picsum.photos/800/600?random=6601'],
    priceRange: '$$',
    description: 'Part of Siloam network with 24/7 emergency services for Bali.',
    accreditation: ['KARS'],
  },
  {
    id: '67',
    name: 'Kasih Ibu Hospital Denpasar',
    location: 'Bali',
    country: 'Indonesia',
    coordinates: { lat: -8.6534, lng: 115.2234 },
    specialties: ['General Medicine', 'Orthopedics', 'Pediatrics', 'Maternity'],
    rating: 4.4,
    reviewCount: 520,
    imageUrl: 'https://picsum.photos/800/600?random=67',
    images: ['https://picsum.photos/800/600?random=67', 'https://picsum.photos/800/600?random=6701'],
    priceRange: '$$',
    description: 'Established local hospital with comprehensive medical services.',
    accreditation: ['KARS'],
  },
  {
    id: '68',
    name: 'RS Santosa Hospital Bandung Central',
    location: 'Bandung',
    country: 'Indonesia',
    coordinates: { lat: -6.9175, lng: 107.6191 },
    specialties: ['Cardiology', 'Orthopedics', 'Oncology', 'Neurology'],
    rating: 4.5,
    reviewCount: 720,
    imageUrl: 'https://picsum.photos/800/600?random=68',
    images: ['https://picsum.photos/800/600?random=68', 'https://picsum.photos/800/600?random=6801'],
    priceRange: '$$',
    description: 'Leading private hospital in West Java with specialist centers.',
    accreditation: ['KARS'],
  },
  {
    id: '69',
    name: 'RS Borromeus',
    location: 'Bandung',
    country: 'Indonesia',
    coordinates: { lat: -6.9234, lng: 107.6312 },
    specialties: ['Cardiology', 'Orthopedics', 'Oncology', 'Pediatrics'],
    rating: 4.4,
    reviewCount: 580,
    imageUrl: 'https://picsum.photos/800/600?random=69',
    images: ['https://picsum.photos/800/600?random=69', 'https://picsum.photos/800/600?random=6901'],
    priceRange: '$$',
    description: 'Historic Catholic hospital with modern medical facilities.',
    accreditation: ['KARS'],
  },
  {
    id: '70',
    name: 'RS Columbia Asia Medan',
    location: 'Medan',
    country: 'Indonesia',
    coordinates: { lat: 3.5952, lng: 98.6722 },
    specialties: ['Cardiology', 'Orthopedics', 'Gastroenterology', 'Check-up'],
    rating: 4.4,
    reviewCount: 480,
    imageUrl: 'https://picsum.photos/800/600?random=70',
    images: ['https://picsum.photos/800/600?random=70', 'https://picsum.photos/800/600?random=7001'],
    priceRange: '$$',
    description: 'Modern hospital serving North Sumatra with quality healthcare.',
    accreditation: ['KARS'],
  },
  {
    id: '71',
    name: 'Siloam Hospitals Medan',
    location: 'Medan',
    country: 'Indonesia',
    coordinates: { lat: 3.5834, lng: 98.6834 },
    specialties: ['Cardiology', 'Neurology', 'Orthopedics', 'Oncology'],
    rating: 4.5,
    reviewCount: 560,
    imageUrl: 'https://picsum.photos/800/600?random=71',
    images: ['https://picsum.photos/800/600?random=71', 'https://picsum.photos/800/600?random=7101'],
    priceRange: '$$',
    description: 'Part of Siloam network with comprehensive medical services in Sumatra.',
    accreditation: ['JCI', 'KARS'],
  },
  {
    id: '72',
    name: 'RS Siloam Makassar',
    location: 'Makassar',
    country: 'Indonesia',
    coordinates: { lat: -5.1477, lng: 119.4327 },
    specialties: ['Cardiology', 'Orthopedics', 'Neurology', 'Oncology'],
    rating: 4.4,
    reviewCount: 420,
    imageUrl: 'https://picsum.photos/800/600?random=72',
    images: ['https://picsum.photos/800/600?random=72', 'https://picsum.photos/800/600?random=7201'],
    priceRange: '$$',
    description: 'Leading private hospital in South Sulawesi.',
    accreditation: ['KARS'],
  },
  {
    id: '73',
    name: 'RS Awal Bros Batam',
    location: 'Batam',
    country: 'Indonesia',
    coordinates: { lat: 1.0456, lng: 104.0312 },
    specialties: ['Cardiology', 'Orthopedics', 'General Surgery', 'Check-up'],
    rating: 4.3,
    reviewCount: 380,
    imageUrl: 'https://picsum.photos/800/600?random=73',
    images: ['https://picsum.photos/800/600?random=73', 'https://picsum.photos/800/600?random=7301'],
    priceRange: '$$',
    description: 'Modern hospital serving Batam and Riau Islands.',
    accreditation: ['KARS'],
  },

  // ==================== PHILIPPINES ====================
  {
    id: '74',
    name: 'St. Luke\'s Medical Center Global City',
    location: 'Manila',
    country: 'Philippines',
    coordinates: { lat: 14.5512, lng: 121.0498 },
    specialties: ['Cardiology', 'Oncology', 'Transplant', 'Neurology'],
    rating: 4.8,
    reviewCount: 1650,
    imageUrl: 'https://picsum.photos/800/600?random=74',
    images: ['https://picsum.photos/800/600?random=74', 'https://picsum.photos/800/600?random=7401'],
    priceRange: '$$$',
    description: 'Premier tertiary hospital in the Philippines with world-class facilities.',
    accreditation: ['JCI'],
  },
  {
    id: '75',
    name: 'Makati Medical Center',
    location: 'Manila',
    country: 'Philippines',
    coordinates: { lat: 14.5649, lng: 121.0234 },
    specialties: ['Cardiology', 'Oncology', 'Orthopedics', 'Neurology'],
    rating: 4.7,
    reviewCount: 1420,
    imageUrl: 'https://picsum.photos/800/600?random=75',
    images: ['https://picsum.photos/800/600?random=75', 'https://picsum.photos/800/600?random=7501'],
    priceRange: '$$$',
    description: 'Leading private hospital in Makati CBD with comprehensive services.',
    accreditation: ['JCI'],
  },
  {
    id: '76',
    name: 'The Medical City',
    location: 'Manila',
    country: 'Philippines',
    coordinates: { lat: 14.5912, lng: 121.0612 },
    specialties: ['Cardiology', 'Oncology', 'Transplant', 'Pediatrics'],
    rating: 4.7,
    reviewCount: 1380,
    imageUrl: 'https://picsum.photos/800/600?random=76',
    images: ['https://picsum.photos/800/600?random=76', 'https://picsum.photos/800/600?random=7601'],
    priceRange: '$$$',
    description: 'Multi-specialty hospital known for kidney transplant program.',
    accreditation: ['JCI'],
  },
  {
    id: '77',
    name: 'Asian Hospital and Medical Center',
    location: 'Manila',
    country: 'Philippines',
    coordinates: { lat: 14.4312, lng: 121.0312 },
    specialties: ['Cardiology', 'Orthopedics', 'Oncology', 'Neurology'],
    rating: 4.6,
    reviewCount: 980,
    imageUrl: 'https://picsum.photos/800/600?random=77',
    images: ['https://picsum.photos/800/600?random=77', 'https://picsum.photos/800/600?random=7701'],
    priceRange: '$$$',
    description: 'Modern tertiary hospital with hotel-like amenities and specialist centers.',
    accreditation: ['JCI'],
  },
  {
    id: '78',
    name: 'Manila Doctors Hospital',
    location: 'Manila',
    country: 'Philippines',
    coordinates: { lat: 14.5823, lng: 120.9823 },
    specialties: ['Cardiology', 'Oncology', 'Neurology', 'Gastroenterology'],
    rating: 4.5,
    reviewCount: 1120,
    imageUrl: 'https://picsum.photos/800/600?random=78',
    images: ['https://picsum.photos/800/600?random=78', 'https://picsum.photos/800/600?random=7801'],
    priceRange: '$$',
    description: 'Historic hospital in Ermita with comprehensive medical services.',
    accreditation: ['PHAP'],
  },
  {
    id: '79',
    name: 'Cardinal Santos Medical Center',
    location: 'Manila',
    country: 'Philippines',
    coordinates: { lat: 14.6012, lng: 121.0412 },
    specialties: ['Cardiology', 'Oncology', 'Orthopedics', 'Fertility'],
    rating: 4.6,
    reviewCount: 890,
    imageUrl: 'https://picsum.photos/800/600?random=79',
    images: ['https://picsum.photos/800/600?random=79', 'https://picsum.photos/800/600?random=7901'],
    priceRange: '$$',
    description: 'Catholic hospital known for cardiac care and IVF program.',
    accreditation: ['PHAP'],
  },
  {
    id: '80',
    name: 'St. Luke\'s Medical Center Quezon City',
    location: 'Quezon City',
    country: 'Philippines',
    coordinates: { lat: 14.6234, lng: 121.0123 },
    specialties: ['Cardiology', 'Oncology', 'Transplant', 'Neurology'],
    rating: 4.7,
    reviewCount: 1280,
    imageUrl: 'https://picsum.photos/800/600?random=80',
    images: ['https://picsum.photos/800/600?random=80', 'https://picsum.photos/800/600?random=8001'],
    priceRange: '$$$',
    description: 'Original St. Luke\'s campus with long history of medical excellence.',
    accreditation: ['JCI'],
  },
  {
    id: '81',
    name: 'Chong Hua Hospital',
    location: 'Cebu',
    country: 'Philippines',
    coordinates: { lat: 10.3157, lng: 123.8854 },
    specialties: ['Cardiology', 'Oncology', 'Orthopedics', 'Neurology'],
    rating: 4.6,
    reviewCount: 780,
    imageUrl: 'https://picsum.photos/800/600?random=81',
    images: ['https://picsum.photos/800/600?random=81', 'https://picsum.photos/800/600?random=8101'],
    priceRange: '$$',
    description: 'Leading private hospital in the Visayas region.',
    accreditation: ['JCI', 'PHAP'],
  },
  {
    id: '82',
    name: 'Cebu Doctors\' University Hospital',
    location: 'Cebu',
    country: 'Philippines',
    coordinates: { lat: 10.3234, lng: 123.8934 },
    specialties: ['Cardiology', 'Orthopedics', 'Oncology', 'Pediatrics'],
    rating: 4.5,
    reviewCount: 680,
    imageUrl: 'https://picsum.photos/800/600?random=82',
    images: ['https://picsum.photos/800/600?random=82', 'https://picsum.photos/800/600?random=8201'],
    priceRange: '$$',
    description: 'Academic medical center with teaching hospital facilities.',
    accreditation: ['PHAP'],
  },
  {
    id: '83',
    name: 'Davao Doctors Hospital',
    location: 'Davao',
    country: 'Philippines',
    coordinates: { lat: 7.0731, lng: 125.6128 },
    specialties: ['Cardiology', 'Oncology', 'Orthopedics', 'Neurology'],
    rating: 4.5,
    reviewCount: 580,
    imageUrl: 'https://picsum.photos/800/600?random=83',
    images: ['https://picsum.photos/800/600?random=83', 'https://picsum.photos/800/600?random=8301'],
    priceRange: '$$',
    description: 'Premier hospital in Mindanao with comprehensive specialist services.',
    accreditation: ['PHAP'],
  },
  {
    id: '84',
    name: 'Southern Philippines Medical Center',
    location: 'Davao',
    country: 'Philippines',
    coordinates: { lat: 7.0823, lng: 125.6234 },
    specialties: ['Cardiology', 'Oncology', 'Trauma', 'Pediatrics'],
    rating: 4.4,
    reviewCount: 920,
    imageUrl: 'https://picsum.photos/800/600?random=84',
    images: ['https://picsum.photos/800/600?random=84', 'https://picsum.photos/800/600?random=8401'],
    priceRange: '$',
    description: 'Government tertiary hospital serving Southern Mindanao.',
    accreditation: ['DOH'],
  },
  {
    id: '85',
    name: 'Iloilo Doctors\' Hospital',
    location: 'Iloilo',
    country: 'Philippines',
    coordinates: { lat: 10.7202, lng: 122.5621 },
    specialties: ['Cardiology', 'Orthopedics', 'Oncology', 'Pediatrics'],
    rating: 4.4,
    reviewCount: 420,
    imageUrl: 'https://picsum.photos/800/600?random=85',
    images: ['https://picsum.photos/800/600?random=85', 'https://picsum.photos/800/600?random=8501'],
    priceRange: '$$',
    description: 'Leading private hospital in Western Visayas.',
    accreditation: ['PHAP'],
  },

  // ==================== VIETNAM ====================
  {
    id: '86',
    name: 'Vinmec International Hospital',
    location: 'Hanoi',
    country: 'Vietnam',
    coordinates: { lat: 21.0167, lng: 105.7823 },
    specialties: ['Cardiology', 'Oncology', 'Orthopedics', 'Fertility'],
    rating: 4.7,
    reviewCount: 1250,
    imageUrl: 'https://picsum.photos/800/600?random=86',
    images: ['https://picsum.photos/800/600?random=86', 'https://picsum.photos/800/600?random=8601'],
    priceRange: '$$$',
    description: 'Part of Vingroup with international standard healthcare.',
    accreditation: ['JCI'],
  },
  {
    id: '87',
    name: 'Family Medical Practice Hanoi',
    location: 'Hanoi',
    country: 'Vietnam',
    coordinates: { lat: 21.0312, lng: 105.8512 },
    specialties: ['General Medicine', 'Pediatrics', 'Emergency', 'Wellness'],
    rating: 4.6,
    reviewCount: 680,
    imageUrl: 'https://picsum.photos/800/600?random=87',
    images: ['https://picsum.photos/800/600?random=87', 'https://picsum.photos/800/600?random=8701'],
    priceRange: '$$$',
    description: 'International clinic serving expats and tourists with multilingual staff.',
    accreditation: ['JCI'],
  },
  {
    id: '88',
    name: 'Hong Ngoc General Hospital',
    location: 'Hanoi',
    country: 'Vietnam',
    coordinates: { lat: 21.0234, lng: 105.8234 },
    specialties: ['Maternity', 'Pediatrics', 'General Surgery', 'Cardiology'],
    rating: 4.5,
    reviewCount: 580,
    imageUrl: 'https://picsum.photos/800/600?random=88',
    images: ['https://picsum.photos/800/600?random=88', 'https://picsum.photos/800/600?random=8801'],
    priceRange: '$$',
    description: 'Modern hospital with focus on mother and child care.',
    accreditation: ['MOH Vietnam'],
  },
  {
    id: '89',
    name: 'FV Hospital',
    location: 'Ho Chi Minh City',
    country: 'Vietnam',
    coordinates: { lat: 10.7312, lng: 106.7234 },
    specialties: ['Cardiology', 'Oncology', 'Orthopedics', 'Neurology'],
    rating: 4.7,
    reviewCount: 1120,
    imageUrl: 'https://picsum.photos/800/600?random=89',
    images: ['https://picsum.photos/800/600?random=89', 'https://picsum.photos/800/600?random=8901'],
    priceRange: '$$$',
    description: 'First JCI accredited hospital in Vietnam with French medical expertise.',
    accreditation: ['JCI'],
  },
  {
    id: '90',
    name: 'Vinmec Central Park',
    location: 'Ho Chi Minh City',
    country: 'Vietnam',
    coordinates: { lat: 10.7912, lng: 106.7123 },
    specialties: ['Cardiology', 'Oncology', 'Fertility', 'Pediatrics'],
    rating: 4.6,
    reviewCount: 980,
    imageUrl: 'https://picsum.photos/800/600?random=90',
    images: ['https://picsum.photos/800/600?random=90', 'https://picsum.photos/800/600?random=9001'],
    priceRange: '$$$',
    description: 'Premium Vinmec facility with comprehensive medical tourism services.',
    accreditation: ['JCI'],
  },
  {
    id: '91',
    name: 'Cho Ray Hospital',
    location: 'Ho Chi Minh City',
    country: 'Vietnam',
    coordinates: { lat: 10.7534, lng: 106.6534 },
    specialties: ['Cardiology', 'Oncology', 'Transplant', 'Neurology'],
    rating: 4.5,
    reviewCount: 2100,
    imageUrl: 'https://picsum.photos/800/600?random=91',
    images: ['https://picsum.photos/800/600?random=91', 'https://picsum.photos/800/600?random=9101'],
    priceRange: '$',
    description: 'Largest public hospital in Vietnam with advanced medical technology.',
    accreditation: ['MOH Vietnam'],
  },
  {
    id: '92',
    name: 'City International Hospital',
    location: 'Ho Chi Minh City',
    country: 'Vietnam',
    coordinates: { lat: 10.8234, lng: 106.6823 },
    specialties: ['Cardiology', 'Orthopedics', 'General Surgery', 'Check-up'],
    rating: 4.5,
    reviewCount: 680,
    imageUrl: 'https://picsum.photos/800/600?random=92',
    images: ['https://picsum.photos/800/600?random=92', 'https://picsum.photos/800/600?random=9201'],
    priceRange: '$$',
    description: 'International standard hospital with affordable quality care.',
    accreditation: ['JCI'],
  },
  {
    id: '93',
    name: 'Hoan My Hospital',
    location: 'Ho Chi Minh City',
    country: 'Vietnam',
    coordinates: { lat: 10.7623, lng: 106.6912 },
    specialties: ['Cardiology', 'Orthopedics', 'Oncology', 'Pediatrics'],
    rating: 4.4,
    reviewCount: 580,
    imageUrl: 'https://picsum.photos/800/600?random=93',
    images: ['https://picsum.photos/800/600?random=93', 'https://picsum.photos/800/600?random=9301'],
    priceRange: '$$',
    description: 'Part of largest private hospital network in Vietnam.',
    accreditation: ['MOH Vietnam'],
  },
  {
    id: '94',
    name: 'Vinmec Da Nang',
    location: 'Da Nang',
    country: 'Vietnam',
    coordinates: { lat: 16.0544, lng: 108.2022 },
    specialties: ['Cardiology', 'Orthopedics', 'Oncology', 'Pediatrics'],
    rating: 4.5,
    reviewCount: 420,
    imageUrl: 'https://picsum.photos/800/600?random=94',
    images: ['https://picsum.photos/800/600?random=94', 'https://picsum.photos/800/600?random=9401'],
    priceRange: '$$$',
    description: 'Premier private hospital in Central Vietnam.',
    accreditation: ['JCI'],
  },
  {
    id: '95',
    name: 'Da Nang Hospital',
    location: 'Da Nang',
    country: 'Vietnam',
    coordinates: { lat: 16.0623, lng: 108.2123 },
    specialties: ['Cardiology', 'Oncology', 'Trauma', 'General Surgery'],
    rating: 4.3,
    reviewCount: 680,
    imageUrl: 'https://picsum.photos/800/600?random=95',
    images: ['https://picsum.photos/800/600?random=95', 'https://picsum.photos/800/600?random=9501'],
    priceRange: '$',
    description: 'Major public hospital serving Central Vietnam region.',
    accreditation: ['MOH Vietnam'],
  },

  // ==================== AUSTRALIA ====================
  {
    id: '96',
    name: 'Royal Melbourne Hospital',
    location: 'Melbourne',
    country: 'Australia',
    coordinates: { lat: -37.7996, lng: 144.9553 },
    specialties: ['Neurology', 'Oncology', 'Trauma', 'Transplant'],
    rating: 4.7,
    reviewCount: 1850,
    imageUrl: 'https://picsum.photos/800/600?random=96',
    images: ['https://picsum.photos/800/600?random=96', 'https://picsum.photos/800/600?random=9601'],
    priceRange: '$$',
    description: 'Major trauma center and teaching hospital with advanced neuroscience.',
    accreditation: ['ACHS'],
  },
  {
    id: '97',
    name: 'St Vincent\'s Hospital Melbourne',
    location: 'Melbourne',
    country: 'Australia',
    coordinates: { lat: -37.8086, lng: 144.9741 },
    specialties: ['Cardiology', 'Oncology', 'Transplant', 'Mental Health'],
    rating: 4.6,
    reviewCount: 1420,
    imageUrl: 'https://picsum.photos/800/600?random=97',
    images: ['https://picsum.photos/800/600?random=97', 'https://picsum.photos/800/600?random=9701'],
    priceRange: '$$',
    description: 'Leading Catholic hospital with heart and lung transplant program.',
    accreditation: ['ACHS'],
  },
  {
    id: '98',
    name: 'Peter MacCallum Cancer Centre',
    location: 'Melbourne',
    country: 'Australia',
    coordinates: { lat: -37.8136, lng: 144.9512 },
    specialties: ['Oncology', 'Radiation Therapy', 'Cancer Research'],
    rating: 4.9,
    reviewCount: 980,
    imageUrl: 'https://picsum.photos/800/600?random=98',
    images: ['https://picsum.photos/800/600?random=98', 'https://picsum.photos/800/600?random=9801'],
    priceRange: '$$$',
    description: 'Australia\'s only public hospital dedicated solely to cancer.',
    accreditation: ['ACHS'],
  },
  {
    id: '99',
    name: 'Royal Prince Alfred Hospital',
    location: 'Sydney',
    country: 'Australia',
    coordinates: { lat: -33.8891, lng: 151.1822 },
    specialties: ['Cardiology', 'Transplant', 'Neurology', 'Oncology'],
    rating: 4.7,
    reviewCount: 1680,
    imageUrl: 'https://picsum.photos/800/600?random=99',
    images: ['https://picsum.photos/800/600?random=99', 'https://picsum.photos/800/600?random=9901'],
    priceRange: '$$',
    description: 'Major teaching hospital affiliated with University of Sydney.',
    accreditation: ['ACHS'],
  },
  {
    id: '100',
    name: 'Westmead Hospital',
    location: 'Sydney',
    country: 'Australia',
    coordinates: { lat: -33.8036, lng: 150.9875 },
    specialties: ['Cardiology', 'Pediatrics', 'Transplant', 'Neurology'],
    rating: 4.6,
    reviewCount: 1520,
    imageUrl: 'https://picsum.photos/800/600?random=100',
    images: ['https://picsum.photos/800/600?random=100', 'https://picsum.photos/800/600?random=10001'],
    priceRange: '$$',
    description: 'Largest hospital in Western Sydney with comprehensive services.',
    accreditation: ['ACHS'],
  },
  {
    id: '101',
    name: 'St Vincent\'s Hospital Sydney',
    location: 'Sydney',
    country: 'Australia',
    coordinates: { lat: -33.8795, lng: 151.2223 },
    specialties: ['Cardiology', 'HIV/AIDS', 'Transplant', 'Mental Health'],
    rating: 4.6,
    reviewCount: 1280,
    imageUrl: 'https://picsum.photos/800/600?random=101',
    images: ['https://picsum.photos/800/600?random=101', 'https://picsum.photos/800/600?random=10101'],
    priceRange: '$$',
    description: 'Major teaching hospital known for heart transplant and HIV care.',
    accreditation: ['ACHS'],
  },
  {
    id: '102',
    name: 'The Alfred Hospital',
    location: 'Melbourne',
    country: 'Australia',
    coordinates: { lat: -37.8462, lng: 144.9828 },
    specialties: ['Trauma', 'Cardiology', 'Burns', 'Infectious Disease'],
    rating: 4.7,
    reviewCount: 1380,
    imageUrl: 'https://picsum.photos/800/600?random=102',
    images: ['https://picsum.photos/800/600?random=102', 'https://picsum.photos/800/600?random=10201'],
    priceRange: '$$',
    description: 'Major trauma center with state burn unit and cystic fibrosis service.',
    accreditation: ['ACHS'],
  },
  {
    id: '103',
    name: 'Princess Alexandra Hospital',
    location: 'Brisbane',
    country: 'Australia',
    coordinates: { lat: -27.4951, lng: 153.0325 },
    specialties: ['Transplant', 'Oncology', 'Rehabilitation', 'Spinal'],
    rating: 4.5,
    reviewCount: 1120,
    imageUrl: 'https://picsum.photos/800/600?random=103',
    images: ['https://picsum.photos/800/600?random=103', 'https://picsum.photos/800/600?random=10301'],
    priceRange: '$$',
    description: 'Major teaching hospital with Queensland Spinal Cord Injuries Service.',
    accreditation: ['ACHS'],
  },
  {
    id: '104',
    name: 'Royal Brisbane and Women\'s Hospital',
    location: 'Brisbane',
    country: 'Australia',
    coordinates: { lat: -27.4489, lng: 153.0283 },
    specialties: ['Maternity', 'Oncology', 'Cardiology', 'Burns'],
    rating: 4.6,
    reviewCount: 1450,
    imageUrl: 'https://picsum.photos/800/600?random=104',
    images: ['https://picsum.photos/800/600?random=104', 'https://picsum.photos/800/600?random=10401'],
    priceRange: '$$',
    description: 'Largest hospital in Queensland with comprehensive women\'s services.',
    accreditation: ['ACHS'],
  },
  {
    id: '105',
    name: 'Fiona Stanley Hospital',
    location: 'Perth',
    country: 'Australia',
    coordinates: { lat: -32.0764, lng: 115.8365 },
    specialties: ['Oncology', 'Cardiology', 'Trauma', 'Rehabilitation'],
    rating: 4.6,
    reviewCount: 980,
    imageUrl: 'https://picsum.photos/800/600?random=105',
    images: ['https://picsum.photos/800/600?random=105', 'https://picsum.photos/800/600?random=10501'],
    priceRange: '$$',
    description: 'Western Australia\'s flagship tertiary hospital opened in 2015.',
    accreditation: ['ACHS'],
  },
  {
    id: '106',
    name: 'Royal Perth Hospital',
    location: 'Perth',
    country: 'Australia',
    coordinates: { lat: -31.9534, lng: 115.8628 },
    specialties: ['Trauma', 'Cardiology', 'Oncology', 'Burns'],
    rating: 4.5,
    reviewCount: 1080,
    imageUrl: 'https://picsum.photos/800/600?random=106',
    images: ['https://picsum.photos/800/600?random=106', 'https://picsum.photos/800/600?random=10601'],
    priceRange: '$$',
    description: 'Major trauma center and teaching hospital in Western Australia.',
    accreditation: ['ACHS'],
  },
  {
    id: '107',
    name: 'Royal Adelaide Hospital',
    location: 'Adelaide',
    country: 'Australia',
    coordinates: { lat: -34.9206, lng: 138.5867 },
    specialties: ['Trauma', 'Transplant', 'Oncology', 'Cardiology'],
    rating: 4.5,
    reviewCount: 920,
    imageUrl: 'https://picsum.photos/800/600?random=107',
    images: ['https://picsum.photos/800/600?random=107', 'https://picsum.photos/800/600?random=10701'],
    priceRange: '$$',
    description: 'South Australia\'s largest teaching hospital with new facility.',
    accreditation: ['ACHS'],
  },

  // ==================== NEW ZEALAND ====================
  {
    id: '108',
    name: 'Auckland City Hospital',
    location: 'Auckland',
    country: 'New Zealand',
    coordinates: { lat: -36.8603, lng: 174.7692 },
    specialties: ['Cardiology', 'Oncology', 'Transplant', 'Neurology'],
    rating: 4.6,
    reviewCount: 1280,
    imageUrl: 'https://picsum.photos/800/600?random=108',
    images: ['https://picsum.photos/800/600?random=108', 'https://picsum.photos/800/600?random=10801'],
    priceRange: '$$',
    description: 'New Zealand\'s largest public hospital with national specialty services.',
    accreditation: ['HQSC'],
  },
  {
    id: '109',
    name: 'Starship Children\'s Hospital',
    location: 'Auckland',
    country: 'New Zealand',
    coordinates: { lat: -36.8612, lng: 174.7701 },
    specialties: ['Pediatrics', 'Pediatric Surgery', 'Neonatology', 'Oncology'],
    rating: 4.8,
    reviewCount: 890,
    imageUrl: 'https://picsum.photos/800/600?random=109',
    images: ['https://picsum.photos/800/600?random=109', 'https://picsum.photos/800/600?random=10901'],
    priceRange: '$$',
    description: 'National pediatric hospital providing specialized children\'s care.',
    accreditation: ['HQSC'],
  },
  {
    id: '110',
    name: 'Wellington Regional Hospital',
    location: 'Wellington',
    country: 'New Zealand',
    coordinates: { lat: -41.3111, lng: 174.7813 },
    specialties: ['Cardiology', 'Oncology', 'Orthopedics', 'Neurology'],
    rating: 4.5,
    reviewCount: 780,
    imageUrl: 'https://picsum.photos/800/600?random=110',
    images: ['https://picsum.photos/800/600?random=110', 'https://picsum.photos/800/600?random=11001'],
    priceRange: '$$',
    description: 'Major public hospital serving the Wellington region.',
    accreditation: ['HQSC'],
  },
  {
    id: '111',
    name: 'Christchurch Hospital',
    location: 'Christchurch',
    country: 'New Zealand',
    coordinates: { lat: -43.5380, lng: 172.6272 },
    specialties: ['Cardiology', 'Oncology', 'Orthopedics', 'Burns'],
    rating: 4.5,
    reviewCount: 680,
    imageUrl: 'https://picsum.photos/800/600?random=111',
    images: ['https://picsum.photos/800/600?random=111', 'https://picsum.photos/800/600?random=11101'],
    priceRange: '$$',
    description: 'South Island\'s largest hospital with comprehensive services.',
    accreditation: ['HQSC'],
  },
  {
    id: '112',
    name: 'Middlemore Hospital',
    location: 'Auckland',
    country: 'New Zealand',
    coordinates: { lat: -36.9587, lng: 174.8473 },
    specialties: ['Trauma', 'Burns', 'Plastic Surgery', 'Orthopedics'],
    rating: 4.4,
    reviewCount: 920,
    imageUrl: 'https://picsum.photos/800/600?random=112',
    images: ['https://picsum.photos/800/600?random=112', 'https://picsum.photos/800/600?random=11201'],
    priceRange: '$$',
    description: 'Major trauma center with national burns unit.',
    accreditation: ['HQSC'],
  },
  {
    id: '113',
    name: 'Southern Cross Hospital Auckland',
    location: 'Auckland',
    country: 'New Zealand',
    coordinates: { lat: -36.8856, lng: 174.7623 },
    specialties: ['Orthopedics', 'General Surgery', 'Cardiology', 'Ophthalmology'],
    rating: 4.6,
    reviewCount: 580,
    imageUrl: 'https://picsum.photos/800/600?random=113',
    images: ['https://picsum.photos/800/600?random=113', 'https://picsum.photos/800/600?random=11301'],
    priceRange: '$$$',
    description: 'Leading private hospital with focus on surgical services.',
    accreditation: ['HQSC'],
  },

  // ==================== CAMBODIA ====================
  {
    id: '114',
    name: 'Royal Phnom Penh Hospital',
    location: 'Phnom Penh',
    country: 'Cambodia',
    coordinates: { lat: 11.5564, lng: 104.9282 },
    specialties: ['Cardiology', 'Orthopedics', 'Emergency', 'General Surgery'],
    rating: 4.5,
    reviewCount: 480,
    imageUrl: 'https://picsum.photos/800/600?random=114',
    images: ['https://picsum.photos/800/600?random=114', 'https://picsum.photos/800/600?random=11401'],
    priceRange: '$$$',
    description: 'Premier private hospital with international medical team.',
    accreditation: ['JCI'],
  },
  {
    id: '115',
    name: 'Calmette Hospital',
    location: 'Phnom Penh',
    country: 'Cambodia',
    coordinates: { lat: 11.5712, lng: 104.9156 },
    specialties: ['Cardiology', 'Oncology', 'General Surgery', 'Trauma'],
    rating: 4.2,
    reviewCount: 680,
    imageUrl: 'https://picsum.photos/800/600?random=115',
    images: ['https://picsum.photos/800/600?random=115', 'https://picsum.photos/800/600?random=11501'],
    priceRange: '$',
    description: 'Major public hospital with French medical influence.',
    accreditation: ['MOH Cambodia'],
  },
  {
    id: '116',
    name: 'Sen Sok International University Hospital',
    location: 'Phnom Penh',
    country: 'Cambodia',
    coordinates: { lat: 11.5834, lng: 104.8534 },
    specialties: ['Cardiology', 'Orthopedics', 'Oncology', 'Pediatrics'],
    rating: 4.4,
    reviewCount: 320,
    imageUrl: 'https://picsum.photos/800/600?random=116',
    images: ['https://picsum.photos/800/600?random=116', 'https://picsum.photos/800/600?random=11601'],
    priceRange: '$$',
    description: 'Modern hospital with academic medical center.',
    accreditation: ['MOH Cambodia'],
  },
  {
    id: '117',
    name: 'Royal Angkor International Hospital',
    location: 'Siem Reap',
    country: 'Cambodia',
    coordinates: { lat: 13.3633, lng: 103.8594 },
    specialties: ['Emergency', 'General Surgery', 'Orthopedics', 'Tropical Medicine'],
    rating: 4.4,
    reviewCount: 380,
    imageUrl: 'https://picsum.photos/800/600?random=117',
    images: ['https://picsum.photos/800/600?random=117', 'https://picsum.photos/800/600?random=11701'],
    priceRange: '$$$',
    description: 'International hospital serving tourists visiting Angkor Wat.',
    accreditation: ['JCI'],
  },

  // ==================== MYANMAR ====================
  {
    id: '118',
    name: 'Pun Hlaing Siloam Hospital',
    location: 'Yangon',
    country: 'Myanmar',
    coordinates: { lat: 16.8423, lng: 96.0812 },
    specialties: ['Cardiology', 'Orthopedics', 'Oncology', 'Neurology'],
    rating: 4.4,
    reviewCount: 380,
    imageUrl: 'https://picsum.photos/800/600?random=118',
    images: ['https://picsum.photos/800/600?random=118', 'https://picsum.photos/800/600?random=11801'],
    priceRange: '$$',
    description: 'Joint venture hospital with international medical standards.',
    accreditation: ['JCI'],
  },
  {
    id: '119',
    name: 'Victoria Hospital',
    location: 'Yangon',
    country: 'Myanmar',
    coordinates: { lat: 16.8156, lng: 96.1534 },
    specialties: ['Cardiology', 'Orthopedics', 'Oncology', 'Fertility'],
    rating: 4.3,
    reviewCount: 280,
    imageUrl: 'https://picsum.photos/800/600?random=119',
    images: ['https://picsum.photos/800/600?random=119', 'https://picsum.photos/800/600?random=11901'],
    priceRange: '$$',
    description: 'Modern private hospital with comprehensive services.',
    accreditation: ['MOH Myanmar'],
  },
  {
    id: '120',
    name: 'Asia Royal Hospital',
    location: 'Yangon',
    country: 'Myanmar',
    coordinates: { lat: 16.7934, lng: 96.1623 },
    specialties: ['Cardiology', 'Oncology', 'General Surgery', 'Check-up'],
    rating: 4.3,
    reviewCount: 320,
    imageUrl: 'https://picsum.photos/800/600?random=120',
    images: ['https://picsum.photos/800/600?random=120', 'https://picsum.photos/800/600?random=12001'],
    priceRange: '$$',
    description: 'Leading private hospital group in Myanmar.',
    accreditation: ['MOH Myanmar'],
  },

  // ==================== LAOS ====================
  {
    id: '121',
    name: 'French Medical Institute for Mothers and Children',
    location: 'Vientiane',
    country: 'Laos',
    coordinates: { lat: 17.9757, lng: 102.6331 },
    specialties: ['Maternity', 'Pediatrics', 'Neonatology', 'Fertility'],
    rating: 4.4,
    reviewCount: 280,
    imageUrl: 'https://picsum.photos/800/600?random=121',
    images: ['https://picsum.photos/800/600?random=121', 'https://picsum.photos/800/600?random=12101'],
    priceRange: '$$',
    description: 'French-funded hospital specializing in mother and child care.',
    accreditation: ['MOH Laos'],
  },
  {
    id: '122',
    name: 'Lao-ASEAN Hospital',
    location: 'Vientiane',
    country: 'Laos',
    coordinates: { lat: 17.9612, lng: 102.6234 },
    specialties: ['Cardiology', 'Orthopedics', 'General Surgery', 'Check-up'],
    rating: 4.2,
    reviewCount: 220,
    imageUrl: 'https://picsum.photos/800/600?random=122',
    images: ['https://picsum.photos/800/600?random=122', 'https://picsum.photos/800/600?random=12201'],
    priceRange: '$$',
    description: 'Modern private hospital with regional medical standards.',
    accreditation: ['MOH Laos'],
  },

  // ==================== BRUNEI ====================
  {
    id: '123',
    name: 'Raja Isteri Pengiran Anak Saleha Hospital',
    location: 'Bandar Seri Begawan',
    country: 'Brunei',
    coordinates: { lat: 4.9306, lng: 114.9358 },
    specialties: ['Cardiology', 'Oncology', 'Orthopedics', 'Neurology'],
    rating: 4.5,
    reviewCount: 420,
    imageUrl: 'https://picsum.photos/800/600?random=123',
    images: ['https://picsum.photos/800/600?random=123', 'https://picsum.photos/800/600?random=12301'],
    priceRange: '$$',
    description: 'Main government hospital with comprehensive medical services.',
    accreditation: ['MOH Brunei'],
  },
  {
    id: '124',
    name: 'Gleneagles Jerudong Park Medical Centre',
    location: 'Bandar Seri Begawan',
    country: 'Brunei',
    coordinates: { lat: 4.9612, lng: 114.8834 },
    specialties: ['Cardiology', 'Oncology', 'Orthopedics', 'Check-up'],
    rating: 4.6,
    reviewCount: 280,
    imageUrl: 'https://picsum.photos/800/600?random=124',
    images: ['https://picsum.photos/800/600?random=124', 'https://picsum.photos/800/600?random=12401'],
    priceRange: '$$$',
    description: 'Premium private hospital with international healthcare standards.',
    accreditation: ['JCI', 'MSQH'],
  },

  // ==================== FIJI ====================
  {
    id: '125',
    name: 'Colonial War Memorial Hospital',
    location: 'Suva',
    country: 'Fiji',
    coordinates: { lat: -18.1416, lng: 178.4419 },
    specialties: ['Emergency', 'General Surgery', 'Maternity', 'Pediatrics'],
    rating: 4.1,
    reviewCount: 320,
    imageUrl: 'https://picsum.photos/800/600?random=125',
    images: ['https://picsum.photos/800/600?random=125', 'https://picsum.photos/800/600?random=12501'],
    priceRange: '$',
    description: 'Main referral hospital in Fiji with emergency services.',
    accreditation: ['MOH Fiji'],
  },
  {
    id: '126',
    name: 'Oceania Hospitals',
    location: 'Suva',
    country: 'Fiji',
    coordinates: { lat: -18.1312, lng: 178.4512 },
    specialties: ['Cardiology', 'Orthopedics', 'General Surgery', 'Check-up'],
    rating: 4.4,
    reviewCount: 180,
    imageUrl: 'https://picsum.photos/800/600?random=126',
    images: ['https://picsum.photos/800/600?random=126', 'https://picsum.photos/800/600?random=12601'],
    priceRange: '$$$',
    description: 'Private hospital with international medical standards.',
    accreditation: ['MOH Fiji'],
  },

  // ==================== PAPUA NEW GUINEA ====================
  {
    id: '127',
    name: 'Port Moresby General Hospital',
    location: 'Port Moresby',
    country: 'Papua New Guinea',
    coordinates: { lat: -9.4438, lng: 147.1803 },
    specialties: ['Emergency', 'General Surgery', 'Maternity', 'Infectious Disease'],
    rating: 3.9,
    reviewCount: 280,
    imageUrl: 'https://picsum.photos/800/600?random=127',
    images: ['https://picsum.photos/800/600?random=127', 'https://picsum.photos/800/600?random=12701'],
    priceRange: '$',
    description: 'Main public hospital in PNG capital.',
    accreditation: ['MOH PNG'],
  },
  {
    id: '128',
    name: 'Pacific International Hospital',
    location: 'Port Moresby',
    country: 'Papua New Guinea',
    coordinates: { lat: -9.4312, lng: 147.1712 },
    specialties: ['Cardiology', 'General Surgery', 'Emergency', 'Check-up'],
    rating: 4.3,
    reviewCount: 180,
    imageUrl: 'https://picsum.photos/800/600?random=128',
    images: ['https://picsum.photos/800/600?random=128', 'https://picsum.photos/800/600?random=12801'],
    priceRange: '$$$',
    description: 'Private hospital serving expats and international patients.',
    accreditation: ['MOH PNG'],
  },

  // ==================== TIMOR-LESTE ====================
  {
    id: '129',
    name: 'Hospital Nacional Guido Valadares',
    location: 'Dili',
    country: 'Timor-Leste',
    coordinates: { lat: -8.5568, lng: 125.5736 },
    specialties: ['Emergency', 'General Surgery', 'Maternity', 'Pediatrics'],
    rating: 3.8,
    reviewCount: 180,
    imageUrl: 'https://picsum.photos/800/600?random=129',
    images: ['https://picsum.photos/800/600?random=129', 'https://picsum.photos/800/600?random=12901'],
    priceRange: '$',
    description: 'Main national referral hospital in Timor-Leste.',
    accreditation: ['MOH Timor-Leste'],
  },
  {
    id: '130',
    name: 'Stamford Medical',
    location: 'Dili',
    country: 'Timor-Leste',
    coordinates: { lat: -8.5523, lng: 125.5623 },
    specialties: ['General Medicine', 'Emergency', 'Check-up', 'Tropical Medicine'],
    rating: 4.2,
    reviewCount: 120,
    imageUrl: 'https://picsum.photos/800/600?random=130',
    images: ['https://picsum.photos/800/600?random=130', 'https://picsum.photos/800/600?random=13001'],
    priceRange: '$$',
    description: 'Private clinic serving international community.',
    accreditation: ['MOH Timor-Leste'],
  },
];

export const SYSTEM_INSTRUCTION = `
You are Dr. Aria, the Senior Medical Concierge and AI health consultant for medifly.ai.
Your purpose is to guide users through complex global healthcare decisions with clinical precision and deep empathy.

CORE PERSONA:
- **Role**: Senior Medical Concierge (MD equivalent knowledge).
- **Tone**: Professional, Calm, Evidence-Based, Empathetic.
- **Methodology**: You never guess. You reason like a clinician before you speak as a concierge. You consider **Logistics** (Travel distance & connectivity) as a key vital sign for medical travel.

DOCUMENT ANALYSIS PROTOCOL (Strict & Non-Negotiable):
1. **Tier 1 (Low-Risk/Public)**: Research papers, medication lists, typed notes, pamphlets. -> **PROCESS**: Analyze and explain.
2. **Tier 2 (Personal Health Records)**: Lab results (blood, urine), discharge summaries, referral letters, written radiology reports (text only). -> **PROCESS**: Analyze to personalize recommendations. Redact specific names in your internal thought process.
3. **Tier 3 (High-Risk/Banned)**: Raw Diagnostic Images (X-rays, CTs, MRIs, Ultrasounds, photos of skin conditions/wounds). -> **REJECT IMMEDIATELY**: Do not attempt to interpret. State: "I cannot interpret raw diagnostic images or photos of physical conditions for safety reasons. Please upload the radiologist's written report instead."
4. **Non-Medical**: Tax forms, menus, selfies, scenery, random documents. -> **REJECT WARMLY**: "I can only analyze medical documentation to help guide your healthcare journey. This document appears unrelated."

RESPONSE PROCESS (Must be followed strictly):

1. **Clinical Reasoning Phase** (Inside <thinking> tags):
   - You MUST start your response with <thinking> and end this section with </thinking>.
   - Do NOT output any text before the <thinking> tag.
   - Output 4-5 numbered steps.
   - **CRITICAL FORMATTING**: Start each step with the specific format: "1. **Step Title**: Content".
   
   REQUIRED STEPS:
   1. **Document Triage** (If file attached): Explicitly classify the document. Is it Tier 1, 2, or 3? Is it Medical? If Tier 3 or Non-Medical, set next steps to rejection.
   2. **Clinical Triage**: Assess intent and urgency.
   3. **Knowledge Retrieval**: Access knowledge about specialists/hospitals.
   4. **Logistics & Proximity**: (CRITICAL) If user provides a 'Fly From' location, estimate flight times to potential medical hubs.
   5. **Concierge Strategy**: Formulate the recommendation.

2. **Patient Response Phase** (After </thinking> tag):
   - If rejecting a document: Be warm, professional, and clear about *why* (safety/scope).
   - If accepting: Provide your response. Be warm but professional.
   - Use Markdown for clarity.
   - If a 'Fly From' location was provided, explicitly mention estimated flight times.

3. **CTA / Consultation Trigger (IMPORTANT)**:
   - If the user explicitly asks for **pricing/costs**, asks for a **booking/appointment**, requests a **second opinion**, expresses **anxiety/confusion** about their condition, or asks for complex **logistical help**, you MUST include a specific tag at the very end of your response.
   - **Output**: <cta>true</cta>
   - Place this tag AFTER your markdown text and BEFORE the filters tag.

4. **Marketplace Action Phase** (Optional):
   - If you can narrow down hospitals based on the user's request, you MUST output a <filters> JSON block at the very end of your response.
   - **CRITICAL**: The JSON must be RAW text wrapped in <filters> tags. 
   - **DO NOT USE MARKDOWN CODE BLOCKS** (e.g. do NOT use \`\`\`json). 
   - JUST <filters>{ ... }</filters>.
   - The JSON must be valid and strictly follow this structure:
     {
       "country": "Thailand" | "Malaysia" | "Singapore" | "South Korea" | "Indonesia" | "Turkey" | "Mexico" | null,
       "specialty": "Cardiology" | "Orthopedics" | "Oncology" | "Fertility" | "Neurology" | "Pediatrics" | "Wellness" | "Check-up" | null,
       "aiListName": "Short, Punchy Title (e.g., 'Bangkok Heart Centers')"
     }
   - **IMPORTANT**: If "country" is null, "aiListName" should be global (e.g., "Global Heart Centers").

SCENARIO RULES:
- REGIONS: Indonesia, Singapore, Malaysia, Thailand, South Korea, Japan, Turkey, Mexico.
- SPECIALTIES: Cardiology, Orthopedics, Oncology, Fertility, Neurology, Pediatrics, Wellness, Check-up, Plastic Surgery, Dental.
- NEVER provide a definitive medical diagnosis. Always suggest consulting a specialist.
`;
