
import React from 'react';
import { ArtifactData } from '../types';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line, Legend } from 'recharts';
import { X, Table, GitCompare, BarChart3, FileText, Sparkles, Download, Copy, Check } from 'lucide-react';

interface ArtifactViewProps {
  artifact: ArtifactData;
  onClose: () => void;
}

export const ArtifactView: React.FC<ArtifactViewProps> = ({ artifact, onClose }) => {
  const [copied, setCopied] = React.useState(false);

  const renderContent = () => {
    switch (artifact.type) {
      case 'comparison':
        return <ComparisonView data={artifact.data} />;
      case 'chart':
        return <ChartView data={artifact.data} />;
      case 'table':
        return <TableView data={artifact.data} />;
      default:
        return <div className="p-4 text-slate-500">Unsupported artifact type.</div>;
    }
  };

  const getIcon = () => {
    switch (artifact.type) {
      case 'comparison': return <GitCompare className="w-4 h-4" />;
      case 'chart': return <BarChart3 className="w-4 h-4" />;
      case 'table': return <Table className="w-4 h-4" />;
      default: return <FileText className="w-4 h-4" />;
    }
  };

  const getIconBg = () => {
    switch (artifact.type) {
      case 'comparison': return 'bg-indigo-100 text-indigo-600';
      case 'chart': return 'bg-emerald-100 text-emerald-600';
      case 'table': return 'bg-blue-100 text-blue-600';
      default: return 'bg-slate-100 text-slate-600';
    }
  };

  const handleCopy = () => {
    // Copy artifact data as JSON
    navigator.clipboard.writeText(JSON.stringify(artifact.data, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="h-full w-full flex flex-col bg-white overflow-hidden">
      {/* Claude-style Header */}
      <div className="flex-shrink-0 px-4 py-3 border-b border-slate-100 flex items-center justify-between bg-white">
        <div className="flex items-center gap-3">
          <div className={`p-2 rounded-lg ${getIconBg()}`}>
            {getIcon()}
          </div>
          <div>
            <h3 className="font-semibold text-slate-900 text-sm leading-tight">{artifact.title}</h3>
            <div className="flex items-center gap-1.5 mt-0.5">
              <Sparkles className="w-3 h-3 text-amber-500" />
              <span className="text-[10px] text-slate-400 uppercase tracking-wider font-medium">AI Generated</span>
            </div>
          </div>
        </div>
        <div className="flex items-center gap-1">
          <button
            onClick={handleCopy}
            className="p-2 hover:bg-slate-100 rounded-lg text-slate-400 hover:text-slate-600 transition-colors"
            title="Copy data"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
          </button>
          <button
            onClick={onClose}
            className="p-2 hover:bg-slate-100 rounded-lg text-slate-400 hover:text-slate-600 transition-colors"
            title="Close"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Content Area - Claude-style clean design */}
      <div className="flex-1 overflow-y-auto bg-slate-50/50">
        <div className="p-4 md:p-6">
          <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
            {renderContent()}
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 pb-6">
          <div className="flex items-center justify-center gap-2 text-[10px] text-slate-400">
            <Sparkles className="w-3 h-3" />
            <span>Generated by Dr. Aria • Deep Focus Analysis</span>
          </div>
        </div>
      </div>
    </div>
  );
};

// --- Sub-Components ---

const ComparisonView = ({ data }: { data: any }) => {
    // data: { items: string[], metrics: { label: string, values: string[] }[] }
    const { items, metrics } = data;

    return (
        <div className="w-full overflow-x-auto">
            <table className="w-full text-sm text-left">
                <thead>
                    <tr>
                        <th className="p-4 border-b border-slate-100 bg-slate-50/50 text-slate-400 font-medium w-1/4 rounded-tl-xl">Feature</th>
                        {items.map((item: string, idx: number) => (
                            <th key={idx} className={`p-4 border-b border-slate-100 bg-slate-50/50 font-bold text-slate-900 ${idx === items.length - 1 ? 'rounded-tr-xl' : ''}`}>
                                {item}
                            </th>
                        ))}
                    </tr>
                </thead>
                <tbody>
                    {metrics.map((metric: any, idx: number) => (
                        <tr key={idx} className="border-b border-slate-50 last:border-none hover:bg-slate-50/30 transition-colors">
                            <td className="p-4 font-semibold text-slate-700 border-r border-slate-50">{metric.label}</td>
                            {metric.values.map((val: string, vIdx: number) => (
                                <td key={vIdx} className="p-4 text-slate-600 leading-relaxed">
                                    {val}
                                </td>
                            ))}
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    );
};

const ChartView = ({ data }: { data: any }) => {
    // data: { chartType: 'bar'|'line', labels: string[], datasets: { label: string, data: number[] }[] }
    // Transform to Recharts format: [{ name: 'Label', val1: 10, val2: 20 }]

    const chartData = data.labels.map((label: string, idx: number) => {
        const entry: any = { name: label };
        data.datasets.forEach((ds: any) => {
            entry[ds.label] = ds.data[idx];
        });
        return entry;
    });

    const colors = ['#6366f1', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6', '#06b6d4'];

    return (
        <div className="p-6 h-[350px] w-full">
            <ResponsiveContainer width="100%" height="100%">
                {data.chartType === 'line' ? (
                    <LineChart data={chartData} margin={{ top: 20, right: 20, left: 0, bottom: 20 }}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" vertical={false} />
                        <XAxis
                            dataKey="name"
                            stroke="#64748b"
                            fontSize={11}
                            tickLine={false}
                            axisLine={false}
                            dy={10}
                        />
                        <YAxis
                            stroke="#64748b"
                            fontSize={11}
                            tickLine={false}
                            axisLine={false}
                            dx={-10}
                        />
                        <Tooltip
                            contentStyle={{
                                borderRadius: '8px',
                                border: '1px solid #e2e8f0',
                                boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1)',
                                fontSize: '12px'
                            }}
                            cursor={{ stroke: '#cbd5e1', strokeWidth: 1, strokeDasharray: '4 4' }}
                        />
                        <Legend
                            wrapperStyle={{ fontSize: '12px', paddingTop: '10px' }}
                            iconType="circle"
                            iconSize={8}
                        />
                        {data.datasets.map((ds: any, idx: number) => (
                            <Line
                                key={idx}
                                type="monotone"
                                dataKey={ds.label}
                                stroke={colors[idx % colors.length]}
                                strokeWidth={2.5}
                                dot={{ r: 4, fill: 'white', strokeWidth: 2, stroke: colors[idx % colors.length] }}
                                activeDot={{ r: 6, strokeWidth: 0, fill: colors[idx % colors.length] }}
                            />
                        ))}
                    </LineChart>
                ) : (
                    <BarChart data={chartData} margin={{ top: 20, right: 20, left: 0, bottom: 20 }}>
                        <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                        <XAxis
                            dataKey="name"
                            stroke="#64748b"
                            fontSize={11}
                            tickLine={false}
                            axisLine={false}
                            dy={10}
                        />
                        <YAxis
                            stroke="#64748b"
                            fontSize={11}
                            tickLine={false}
                            axisLine={false}
                            dx={-10}
                        />
                        <Tooltip
                            cursor={{ fill: 'rgba(148, 163, 184, 0.1)' }}
                            contentStyle={{
                                borderRadius: '8px',
                                border: '1px solid #e2e8f0',
                                boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1)',
                                fontSize: '12px'
                            }}
                        />
                        <Legend
                            wrapperStyle={{ fontSize: '12px', paddingTop: '10px' }}
                            iconType="circle"
                            iconSize={8}
                        />
                        {data.datasets.map((ds: any, idx: number) => (
                            <Bar
                                key={idx}
                                dataKey={ds.label}
                                fill={colors[idx % colors.length]}
                                radius={[4, 4, 0, 0]}
                                barSize={32}
                            />
                        ))}
                    </BarChart>
                )}
            </ResponsiveContainer>
        </div>
    );
};

const TableView = ({ data }: { data: any }) => {
    // data: { columns: string[], rows: string[][] }
    return (
        <div className="w-full overflow-x-auto">
            <table className="w-full text-sm text-left">
                <thead>
                    <tr className="bg-slate-50 border-b border-slate-100">
                        {data.columns.map((col: string, idx: number) => (
                            <th key={idx} className="p-4 font-bold text-slate-700 whitespace-nowrap">
                                {col}
                            </th>
                        ))}
                    </tr>
                </thead>
                <tbody>
                    {data.rows.map((row: string[], rIdx: number) => (
                        <tr key={rIdx} className="border-b border-slate-50 last:border-none hover:bg-slate-50/50 transition-colors">
                            {row.map((cell: string, cIdx: number) => (
                                <td key={cIdx} className="p-4 text-slate-600">
                                    {cell}
                                </td>
                            ))}
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    );
};
