
import React from 'react';
import { ArtifactData } from '../types';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line } from 'recharts';
import { X, ExternalLink, ArrowRight, Table, GitCompare, BarChart3, FileText } from 'lucide-react';

interface ArtifactViewProps {
  artifact: ArtifactData;
  onClose: () => void;
}

export const ArtifactView: React.FC<ArtifactViewProps> = ({ artifact, onClose }) => {
  
  const renderContent = () => {
    switch (artifact.type) {
      case 'comparison':
        return <ComparisonView data={artifact.data} />;
      case 'chart':
        return <ChartView data={artifact.data} />;
      case 'table':
        return <TableView data={artifact.data} />;
      default:
        return <div className="p-4 text-slate-500">Unsupported artifact type.</div>;
    }
  };

  const getIcon = () => {
      switch (artifact.type) {
          case 'comparison': return <GitCompare className="w-5 h-5 text-indigo-500" />;
          case 'chart': return <BarChart3 className="w-5 h-5 text-emerald-500" />;
          case 'table': return <Table className="w-5 h-5 text-blue-500" />;
          default: return <FileText className="w-5 h-5 text-slate-500" />;
      }
  };

  return (
    <div className="h-full flex flex-col bg-white overflow-hidden rounded-l-2xl shadow-2xl border-l border-slate-100 animate-in slide-in-from-right duration-500">
      {/* Header */}
      <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between bg-slate-50/50">
        <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-white rounded-lg border border-slate-200 flex items-center justify-center shadow-sm">
                {getIcon()}
            </div>
            <div>
                <h3 className="font-bold text-slate-900 leading-tight">{artifact.title}</h3>
                <p className="text-xs text-slate-500 uppercase tracking-wide font-medium">Deep Focus Artifact</p>
            </div>
        </div>
        <button 
          onClick={onClose}
          className="p-2 hover:bg-white rounded-full text-slate-400 hover:text-slate-600 transition-colors"
        >
          <X className="w-5 h-5" />
        </button>
      </div>

      {/* Scrollable Content */}
      <div className="flex-1 overflow-y-auto p-6 md:p-8 bg-slate-50/30">
         <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-1 min-h-[400px]">
            {renderContent()}
         </div>
         
         <div className="mt-6 text-center text-xs text-slate-400">
            Generated by Medifly AI • Clinical Decision Support
         </div>
      </div>
    </div>
  );
};

// --- Sub-Components ---

const ComparisonView = ({ data }: { data: any }) => {
    // data: { items: string[], metrics: { label: string, values: string[] }[] }
    const { items, metrics } = data;

    return (
        <div className="w-full overflow-x-auto">
            <table className="w-full text-sm text-left">
                <thead>
                    <tr>
                        <th className="p-4 border-b border-slate-100 bg-slate-50/50 text-slate-400 font-medium w-1/4 rounded-tl-xl">Feature</th>
                        {items.map((item: string, idx: number) => (
                            <th key={idx} className={`p-4 border-b border-slate-100 bg-slate-50/50 font-bold text-slate-900 ${idx === items.length - 1 ? 'rounded-tr-xl' : ''}`}>
                                {item}
                            </th>
                        ))}
                    </tr>
                </thead>
                <tbody>
                    {metrics.map((metric: any, idx: number) => (
                        <tr key={idx} className="border-b border-slate-50 last:border-none hover:bg-slate-50/30 transition-colors">
                            <td className="p-4 font-semibold text-slate-700 border-r border-slate-50">{metric.label}</td>
                            {metric.values.map((val: string, vIdx: number) => (
                                <td key={vIdx} className="p-4 text-slate-600 leading-relaxed">
                                    {val}
                                </td>
                            ))}
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    );
};

const ChartView = ({ data }: { data: any }) => {
    // data: { chartType: 'bar'|'line', labels: string[], datasets: { label: string, data: number[] }[] }
    // Transform to Recharts format: [{ name: 'Label', val1: 10, val2: 20 }]
    
    const chartData = data.labels.map((label: string, idx: number) => {
        const entry: any = { name: label };
        data.datasets.forEach((ds: any) => {
            entry[ds.label] = ds.data[idx];
        });
        return entry;
    });

    const colors = ['#6366f1', '#10b981', '#f59e0b', '#ef4444'];

    return (
        <div className="p-6 h-[400px] w-full">
            <ResponsiveContainer width="100%" height="100%">
                {data.chartType === 'line' ? (
                    <LineChart data={chartData} margin={{ top: 20, right: 30, left: 0, bottom: 5 }}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
                        <XAxis dataKey="name" stroke="#94a3b8" fontSize={12} tickLine={false} axisLine={false} />
                        <YAxis stroke="#94a3b8" fontSize={12} tickLine={false} axisLine={false} />
                        <Tooltip 
                            contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 4px 12px rgba(0,0,0,0.1)' }}
                            cursor={{ stroke: '#cbd5e1', strokeWidth: 1 }}
                        />
                        {data.datasets.map((ds: any, idx: number) => (
                            <Line 
                                key={idx} 
                                type="monotone" 
                                dataKey={ds.label} 
                                stroke={colors[idx % colors.length]} 
                                strokeWidth={3}
                                dot={{ r: 4, fill: 'white', strokeWidth: 2 }}
                                activeDot={{ r: 6 }}
                            />
                        ))}
                    </LineChart>
                ) : (
                    <BarChart data={chartData} margin={{ top: 20, right: 30, left: 0, bottom: 5 }}>
                        <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                        <XAxis dataKey="name" stroke="#94a3b8" fontSize={12} tickLine={false} axisLine={false} />
                        <YAxis stroke="#94a3b8" fontSize={12} tickLine={false} axisLine={false} />
                        <Tooltip 
                            cursor={{ fill: '#f8fafc' }}
                            contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 4px 12px rgba(0,0,0,0.1)' }}
                        />
                        {data.datasets.map((ds: any, idx: number) => (
                            <Bar 
                                key={idx} 
                                dataKey={ds.label} 
                                fill={colors[idx % colors.length]} 
                                radius={[6, 6, 0, 0]} 
                                barSize={40}
                            />
                        ))}
                    </BarChart>
                )}
            </ResponsiveContainer>
        </div>
    );
};

const TableView = ({ data }: { data: any }) => {
    // data: { columns: string[], rows: string[][] }
    return (
        <div className="w-full overflow-x-auto">
            <table className="w-full text-sm text-left">
                <thead>
                    <tr className="bg-slate-50 border-b border-slate-100">
                        {data.columns.map((col: string, idx: number) => (
                            <th key={idx} className="p-4 font-bold text-slate-700 whitespace-nowrap">
                                {col}
                            </th>
                        ))}
                    </tr>
                </thead>
                <tbody>
                    {data.rows.map((row: string[], rIdx: number) => (
                        <tr key={rIdx} className="border-b border-slate-50 last:border-none hover:bg-slate-50/50 transition-colors">
                            {row.map((cell: string, cIdx: number) => (
                                <td key={cIdx} className="p-4 text-slate-600">
                                    {cell}
                                </td>
                            ))}
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    );
};
